### ISSUE TITLE
warnings, should I fix them?

### ISSUE THREAD

**Issue by unicomp21** [google/filament#5645] opened 2022-06-05 13:34 UTC
-- Build files have been written to: /tmp/filament/out/cmake-webgl-release
[322/582] Building CXX object filament/CMakeFiles/filament.dir/src/details/Scene.cpp.o
/tmp/filament/filament/src/details/Scene.cpp:109:13: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
        if (!ri & !li) {
            ^~~~~~~~~
                &&
/tmp/filament/filament/src/details/Scene.cpp:109:13: note: cast one or both operands to int to silence this warning
1 warning generated.
[351/582] Building C object third_party/civetweb/tnt/CMakeFiles/civetweb.dir/__/src/civetweb.c.o
In file included from /tmp/filament/third_party/civetweb/src/civetweb.c:827:
/tmp/emsdk/upstream/emscripten/cache/sysroot/include/sys/poll.h:1:2: warning: redirecting incorrect #include <sys/poll.h> to <poll.h> [-W#warnings]
#warning redirecting incorrect #include <sys/poll.h> to <poll.h>
 ^
1 warning generated.
[511/582] Building C object third_party/getopt/CMakeFiles/getopt.dir/src/getopt.c.o
/tmp/filament/third_party/getopt/src/getopt.c:54:14: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
static char *_progname(nargv0)
             ^
/tmp/filament/third_party/getopt/src/getopt.c:54:14: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
/tmp/filament/third_party/getopt/src/getopt.c:78:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
int getopt(nargc, nargv, ostr)
    ^
3 warnings generated.
[512/582] Building C object third_party/getopt/CMakeFiles/getopt.dir/src/getopt_long.c.o
/tmp/filament/third_party/getopt/src/getopt_long.c:53:14: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
static char *__progname(nargv0)
             ^
/tmp/filament/third_party/getopt/src/getopt_long.c:53:14: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
/tmp/filament/third_party/getopt/src/getopt_long.c:77:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
int getopt_internal(nargc, nargv, ostr)
    ^
/tmp/filament/third_party/getopt/src/getopt_long.c:160:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
int getopt_long(nargc, nargv, options, long_options, index) int nargc;
    ^
4 warnings generated.

**Comment by romainguy** [comment] 2022-06-05 15:40
The first one is as intended and the other ones are in external libraries and should be fixed upstream or left alone.

**Closed** 2022-06-05 15:41 UTC
