### ISSUE TITLE
[gltf-viewer] Vulkan performance is much worse than OpenGL on Android

### ISSUE THREAD

**Issue by awkr** [google/filament#7091] opened 2023-08-18 10:29 UTC
In my Android device, render a glTF model which has about 300000+ triangles via the gltf-viewer sample, Vulkan has a much lower FPS compared to OpenGL:
- Vulkan avg FPS is 21.6
- OpenGL avg FPS is 44.9

Does anyone know if this is right? In my impression, Vulkan should have better performance, how to adjust it? thx !

**Comment by poweifeng** [comment] 2023-08-18 15:54
duplicate of #7048

**Closed by poweifeng** 2023-08-18 15:54 UTC
