### ISSUE TITLE
Pick api not picking entity with BLEND alphaMode

### ISSUE THREAD

**Issue by mbalajee** [google/filament#7950] opened 2024-06-28 14:40 UTC
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
Am loading a gltf model.  Pick API is not picking the node with `alphaMode = BLEND` in its material.  On selecting this node `fragCoords.z` is 1 and `depth` is 0.  Issue exists in all platforms and in all filament backends

**To Reproduce**
Load a gltf/glb model with a node having `alphaMode = BLEND` set in materials 

**Expected behavior**
Node should be selected

**Screenshots**
<video src="https://github.com/google/filament/assets/17508872/12cc18c9-7bc6-46e6-b4b0-ac648c13412d"/>

**Logs**
(Refer the video)

**Desktop (please complete the following information):**
 - OS: Mac/Android (Haven't tested windows & iOS but i believe they should be affected as well)
 - GPU: Any
 - Backend: OpenGL & Metal (haven't tested with vulkan)

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any

**Additional context**
[gltf_sample.zip](https://github.com/user-attachments/files/16032109/gltf_sample.zip)

**Comment by mbalajee** [comment] 2024-06-28 14:58
Found similar issues discussed previously,
https://github.com/google/filament/discussions/3827#discussioncomment-4549217
https://github.com/google/filament/discussions/7140

I understand this is a limitation cz `pick` API is based on pixel picking so nodes with `alphaMode = BLEND` won't work.  Is there a plan to add this support to filament, or the expectation is to let the users implement it ?

**Comment by pixelflinger** [comment] 2024-06-29 00:31
this is a duplicate of #6614

**Closed by pixelflinger** 2024-06-29 00:31 UTC
Labels: duplicate
