### ISSUE TITLE
Question: share depthbuffer between views

### ISSUE THREAD

**Issue by RYDB3RG** [google/filament#3240] opened 2020-10-31 17:35 UTC
I have 2 views: one main view and one debugview. Into the debugview i draw 3D debugstuff like lines and I would like to have those lines depth-clipped by the mainview's geometry.

If I wasnt using filament, I'd probably solve this by simply using the same depthbuffer for both views.

Is there a way to achive something similar with filament (ideally without rendering models twice) ?

What I've tried so far is to create/set manually created rendertargets that share a depthtarget and attach them to the views. But this gives me only a black screen (I guess nobody writes the swapchain anymore?)

```
        shared_depth.reset(
            filament::Texture::Builder()
                .width(window_size.x)
                .height(window_size.y)
                .format(filament::Texture::InternalFormat::DEPTH32F)
                .usage(filament::Texture::Usage::DEPTH_ATTACHMENT)
                .build(*engine));

        {
            color.reset(
                filament::Texture::Builder()
                    .width(window_size.x)
                    .height(window_size.y)
                    .format(filament::Texture::InternalFormat::RGB16F)
                    .usage(filament::Texture::Usage::COLOR_ATTACHMENT)
                    .build(*engine));

            rendertarget.reset(
                filament::RenderTarget::Builder()
                    .texture(filament::RenderTarget::AttachmentPoint::COLOR, color.get())
                    .texture(filament::RenderTarget::AttachmentPoint::DEPTH, shared_depth.get())
                    .build(*engine));

            view->setCamera(camera.entity.camera);
            view->setScene(scene.get());
            view->setRenderTarget(rendertarget.get());
            view->setViewport(window_viewport);
        }

        {
            dbg_color.reset(
                filament::Texture::Builder()
                    .width(window_size.x)
                    .height(window_size.y)
                    .format(filament::Texture::InternalFormat::RGB16F)
                    .usage(filament::Texture::Usage::COLOR_ATTACHMENT)
                    .build(*engine));

            dbg_rendertarget.reset(
                filament::RenderTarget::Builder()
                    .texture(filament::RenderTarget::AttachmentPoint::COLOR, dbg_color.get())
                    .texture(filament::RenderTarget::AttachmentPoint::DEPTH, shared_depth.get())
                    .build(*engine));

            dbg_view->setCamera(camera.entity.camera);
            dbg_view->setScene(dbg_scene.get());
            dbg_view->setViewport(window_viewport);
            dbg_view->setRenderTarget(dbg_rendertarget.get());
            dbg_view->setPostProcessingEnabled(false);
            dbg_view->setBlendMode(filament::View::BlendMode::TRANSLUCENT);
            dbg_view->setShadowingEnabled(false);
        }
```

**Comment by romainguy** [comment] 2020-10-31 17:41
Duplicate of issue #3145

**Closed** 2020-10-31 17:47 UTC
Labels: duplicate
