### ISSUE TITLE
Filament is no longer working in the newest version of google chrome

### ISSUE THREAD

**Issue by davidwarford** [google/filament#3328] opened 2020-12-01 21:49 UTC
**Describe the bug**
Fails to render in latest version of chrome, both old and new versions of Filament, errors are as follow.
`37[.WebGL-0000021D2E11A040] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.`
`[.WebGL-0000021D2E11A040] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete`

**To Reproduce**
1. Update to the latest version of chrome.
2. Run any web example (the old HexGL example has the same issue as newer examples)

**Expected behavior**
It is expected to render

**Screenshots**
Not much  to screenshot, it's just solid black

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by romainguy** [comment] 2020-12-01 21:52
Duplicate of issue #3308. It seems to only affect Chrome 87 on Windows (other browsers are fine, and Chrome 87 on other OSs is fine as well).

**Closed** 2020-12-01 21:52 UTC
Labels: duplicate

**Comment by davidwarford** [comment] 2020-12-01 21:54
oh. didn't realize it was a duplicate, my bad

**Comment by romainguy** [comment] 2020-12-01 21:58
No worry :) We're the ones who are sorry you are running into this issue.
