### ISSUE TITLE
1.16 may have broken skinmeshes lighting

### ISSUE THREAD

**Issue by teub** [google/filament#5088] opened 2022-01-22 00:56 UTC
**Describe the bug**
I updated from 1.15.2 to 1.16.1 and the lighting of my skin meshes completely broke. It looks as if the normals aren't computed properly, I'm not even sure the light is coming from the correct direction. No problem on static geometries.

- I already rebuilt the materials.
- I don't think I have any kind of scales in my hierarchy

**To Reproduce**
I don't have repro steps and can't provide screenshots yet, this will take me a while to provide (or is there a way to provide screenshots privately?)

I'm opening the ticket as a heads-up and welcoming suggestions if this problem could be on my side.
In the meanwhile I've temporarily reverted to 1.15.2.

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Comment by romainguy** [comment] 2022-01-22 01:48
Could you share a test model by any chance?

**Comment by romainguy** [comment] 2022-01-22 01:52
Lighting seems fine int he couple of skinned meshes I tried (glTF).

**Comment by teub** [comment] 2022-01-24 22:56
Here are side to side of rendering the same cylinder as a static mesh (left) and as a skin mesh (on the right, lighting is wrong). I'll work on a sandbox repro unless this is enough information : 

![image](https://user-images.githubusercontent.com/11277063/150878552-b2e97779-b1cd-49a9-a07f-c3664f737c8c.png)

It just has one bone, imported from this FBX :
[test_mat.zip](https://github.com/google/filament/files/7929405/test_mat.zip)

**Comment by teub** [comment] 2022-01-24 23:20
Same meshes but with a ground : 

![image](https://user-images.githubusercontent.com/11277063/150881143-6d20b042-fbec-4692-837c-6ea1145939c1.png)

In addition to the broken lighting, it looks like the skin mesh isn't casting any shadow (with or without VSM enabled) which could be related to the same problem.

**Comment by romainguy** [comment] 2022-01-24 23:23
Issue #5100 may be related

**Comment by teub** [comment] 2022-01-24 23:25
I'm re-adding the screenshot I made with shadows. Sorry I deleted the comment earlier, it's just because I can see shadows in my non-test case so I wasn't sure this was a real issue and not just my test not setup properly for shadows.

![image](https://user-images.githubusercontent.com/11277063/150881919-8651eb68-afde-40f1-88e5-ed01be1ca3bc.png)

**Comment by pixelflinger** [comment] 2022-01-25 01:00
Do you have a gltf version of the test?

**Comment by teub** [comment] 2022-01-25 01:19
Here's the same file exported as a gltf, hoping it is skinned properly [test_mat_glb.zip](https://github.com/google/filament/files/7929885/test_mat_glb.zip)

**Comment by pixelflinger** [comment] 2022-01-25 01:22
duplicate of #5100 which has a better test.

**Comment by pixelflinger** [comment] 2022-01-25 17:05
I'm reopening this because while related #5100 is a different problem (and probably just an asset problem).
Some discussion fort this bug is recorded in #5100.

**Comment by teub** [comment] 2022-01-25 17:52
My problem was actually the lighting, not the shadows ! The shadow problem appeared in my test scene but not in my application, and indeed I'm doing weird things with bounding boxes for skin meshes for other reasons.
Setting a proper AABB indeed fixes the issue (tested with 1.15.2). Thanks for following up!

**Comment by teub** [comment] 2022-01-25 18:31
Sorry for re-closing the bug, I read a bit too fast. So yeah, the shadow is not an issue. I tested the change above b69546c  along with 1.17.0, lighting still seems to be off in the same way.

I also tried the other thing you mentioned in the other bug, I commented "addSamplerGroup(pb, BindingPoints::PER_RENDERABLE_MORPHING,..." but still no change. Maybe I'm testing this wrong, or does this imply rebuilding materials?

**Comment by teub** [comment] 2022-01-25 19:58
Following the idea from my previous comment here https://github.com/google/filament/issues/5100#issuecomment-1020724262 

I tried just returning "return normalize(n);" in vec3 mulBoneNormal(vec3 n, uint i).
Obviously this is not a fix but doesn't this confirm the issue is with the new bone data packing?

![image](https://user-images.githubusercontent.com/11277063/151049946-431728aa-c26e-4b69-9740-9f96bb553e9f.png)

**Comment by teub** [comment] 2022-01-25 21:00
I tried a few other things, including using bonesUniforms.bones[i].transform to transform the normal and it seems to work : 

>    highp mat4x3 m = transpose(bonesUniforms.bones[i].transform);
>    cof = mat3(m);

>    return normalize(cof * n);

I'm not sure what bonesUniforms.bones[i].cof is for if the transform is in bonesUniforms.bones[i].transform ?

Anyway, I hope this helps

**Comment by pixelflinger** [comment] 2022-01-26 01:04
`bonesUniforms.bones[i].cof` exists so we don't have to calculate the cofactor in the shader, which si pretty expensive.

`cof = mat3(m);` is incorrect though, you need to compute the cofactor matrix.


The biggest problem I have is that I don't have a good repro test. It would be helpful if you could provide a gltf file we can use with `gltf_viewer` that shows the problem.

**Comment by teub** [comment] 2022-01-26 02:45
> The biggest problem I have is that I don't have a good repro test.

So I assume you couldn't reproduce the issue with the glm I exported yesterday ? Glm is a gltf in binary form.
Otherwise I'll probably have to work on setting up a sample to reproduce the issue.

**Comment by teub** [comment] 2022-01-26 03:54
So I made a better gltf scene with both objects and a light : 
[test_mat2.zip](https://github.com/google/filament/files/7938792/test_mat2.zip).

I opened it with gltf_viewer but I can't see the issue, lighting seems fine there. I guess finding what goes wrong in my case and not in gltf_viewer is going to be quite painful.

**Comment by pixelflinger** [comment] 2022-01-26 05:40
Does using the cofactor() computed in the shader fix your issue?

If so, I suspect that you must have very large scaling in your transform, could it be the case?

Try to divide the cof matrix on the CPU side by 10 or 100, and see if it helps.

Thanks!

**Comment by teub** [comment] 2022-01-26 19:02
> Does using the cofactor() computed in the shader fix your issue?

I tried this code you mentioned earlier :

> highp mat4x3 m = transpose(bonesUniforms.bones[i].transform);
> highp mat3 cof = cofactor(mat3(m));
> return normalize(cof * n);

It doesn't fix the issue; this is the result (which seems to be the same than the initial issue) :

![image](https://user-images.githubusercontent.com/11277063/151216282-b36e1637-a37a-4377-b492-b12f6d09e371.png)

> Try to divide the cof matrix on the CPU side by 10 or 100, and see if it helps.

cof matrix on the cpu is Identity;
somehow I'm not getting an identity back in the shader.
I have no clue what's happening, I'll keep investigating.

**Comment by teub** [comment] 2022-01-26 20:58
if I replace this:

> vec3 mulBoneNormal(vec3 n, uint i) {
> 
>     highp mat3 cof;
> 
>     // the first 8 elements of the cofactor matrix are stored as fp16
>     highp vec2 zx = unpackHalf2x16(bonesUniforms.bones[i].cof[1]);
>     cof[0].xy = unpackHalf2x16(bonesUniforms.bones[i].cof[0]);
>     cof[0].z = zx[0];
>     cof[1].x = zx[1];
>     cof[1].yz = unpackHalf2x16(bonesUniforms.bones[i].cof[2]);
>     cof[2].xy = unpackHalf2x16(bonesUniforms.bones[i].cof[3]);
> 
>     // the last element must be computed by hand
>     highp float a = bonesUniforms.bones[i].transform[0][0];
>     highp float b = bonesUniforms.bones[i].transform[0][1];
>     highp float d = bonesUniforms.bones[i].transform[1][0];
>     highp float e = bonesUniforms.bones[i].transform[1][1];
> 
>     cof[2].z = a * e - b * d;
> 
>     return normalize(cof * n);
> }

with this :

> vec3 mulBoneNormal(vec3 n, uint i) {
> 
>     highp mat3 cof;
> 
>     // the first 8 elements of the cofactor matrix are stored as fp16
>     highp vec2 x0y0 = unpackHalf2x16(bonesUniforms.bones[i].cof[0]);
>     highp vec2 z0x1 = unpackHalf2x16(bonesUniforms.bones[i].cof[1]);
>     highp vec2 y1z1 = unpackHalf2x16(bonesUniforms.bones[i].cof[2]);
>     highp vec2 x2y2 = unpackHalf2x16(bonesUniforms.bones[i].cof[3]);
> 
>     // the last element must be computed by hand
>     highp float a = bonesUniforms.bones[i].transform[0][0];
>     highp float b = bonesUniforms.bones[i].transform[0][1];
>     highp float d = bonesUniforms.bones[i].transform[1][0];
>     highp float e = bonesUniforms.bones[i].transform[1][1];
> 
>     cof[2].z = a * e - b * d;
> 
>     cof[0].xyz = vec3(x0y0, z0x1.x);
>     cof[1].xyz = vec3(z0x1.y, y1z1.x, y1z1.y);
>     cof[2].xyz = vec3(x2y2, a * e - b * d);
> 
> 
>     return normalize(cof * n);
> }
> 

Then it works. The problem is, I have no clue on why it'd give a different result ?

**Comment by teub** [comment] 2022-01-26 21:22
Side note: among my tests, some code as simple as this failed, whereas the xyz version "worked" to get me an identity matrix. I'm looking for some opengl doc to know what is legal and what is not but I'm not finding much.

> cof[0].xy = vec2(1, 0);
> cof[0].z = 0.0;
> cof[1].x = 0.0;
> cof[1].yz = vec2(1, 0);
> cof[2].xy = vec2(0, 0);
> cof[2].z = 1.0;

**Comment by pixelflinger** [comment] 2022-01-26 21:37
Wow. Thank you for the investigation.

This definitely look like compiler bugs to me.

**Comment by pixelflinger** [comment] 2022-01-26 21:39
Would you like to submit a PR with your version that works?

If not I can do it.

**Comment by teub** [comment] 2022-01-26 21:45
I don't have a fork so I don't think I can create a PR

**Comment by teub** [comment] 2022-01-26 21:48
Note: there are still a few mysteries pending, including why using cofactor() in the shader gave the same wrong result, or why I couldn't reproduce the problem with gltf_viewer. I'll do some more check for the latter, because if I can provide a repro for you to test it'd be nice.

**Comment by teub** [comment] 2022-01-26 22:57
Good news, the problem can actually be reproduced with gltf_viewer (at least on my machine), but care must be taken to enable optimizations for matc : see the FILAMENT_DISABLE_MATOPT flag. When using cmake by default, it generated unoptimized versions of the shaders and that's why I couldn't see the problem with gltf viewer, wherease I didn't have the -gd flag for my own materials.

![image](https://user-images.githubusercontent.com/11277063/151261025-ca137ef2-9b1e-4089-8733-ab5b573dd72a.png)

**Comment by romainguy** [comment] 2022-01-26 22:58
`-g` *disables* material optimizations. Debug builds turn material optimizations off by default, release builds turn them on.

**Comment by teub** [comment] 2022-01-26 23:00
> `-g` _disables_ material optimizations. Debug builds turn material optimizations off by default, release builds turn them on.

Yes and "CMake .." generates debug commands, for both the debug and release config of TNT.sln

**Comment by romainguy** [comment] 2022-01-26 23:00
So is the issue with optimizations on or off?

**Comment by teub** [comment] 2022-01-26 23:01
On

**Comment by teub** [comment] 2022-01-26 23:06
I'm on nvidia drivers 510.06 if that matters

**Comment by pixelflinger** [comment] 2022-01-27 00:43
ah yeah... the optimizer does really really strange things with matrices -- that rings a bell.

**Comment by pixelflinger** [comment] 2022-01-28 00:36
argh I'm still not able to reproduce it in our gltf_viewer.

**Closed** 2022-01-28 03:24 UTC
Labels: bug

**Comment by teub** [comment] 2022-01-28 09:42
@pixelflinger there was also the same problem with the "cofactor" function which exhibited the same issue, and - I guess - any other shader code that accesses matrix members in the same way, but I haven't reviewed them all.
