### ISSUE TITLE
Named materials not working [Web]

### ISSUE THREAD

**Issue by Amit-Tomar** [google/filament#663] opened 2018-12-24 10:30 UTC
**Describe the bug**
Trying to render a filamesh which has material name 'Material__25' in it. 

When loading like this, it works fine, the default texture gets applied : 

`const filamesh = this.engine.loadFilamesh(this.filamesh_url, this.matinstance);
`

However, when I want to pass a map of material , none of the texture is getting applied. 

`const filamesh = this.engine.loadFilamesh(this.filamesh_url, undefined , {'Material__25':this.matinstance});`

Model is a cube, and this how it shows : 

![screenshot from 2018-12-26 12-40-50](https://user-images.githubusercontent.com/5795958/50436379-a770f980-090b-11e9-94ab-c6c6866cce9c.png)

**Expected behavior**
Documentation says : 

> engine.loadFilamesh(buffer, definstance, matinstances)
> Consumes the contents of a filamesh file and creates a renderable.
> buffer asset string, or Uint8Array, or Buffer with filamesh contents
> definstance Optional default MaterialInstance
> **matinstances Optional object that gets filled with name => MaterialInstance**
> returns JavaScript object with keys renderable, vertexBuffer, and indexBuffer. These are of type Entity, VertexBuffer, and IndexBuffer.

Am I passing the dictionary correctly in my code or something else is expected to pass the name : matInstance pair. Also, its confusing if the **=>** mentioned here is the new map symbol introduced in ECMA6 or just a symbol to show some sort of relation between left and right hand side.

**Desktop (please complete the following information):**
 - Backend: [Web]

**Comment by prideout** [comment] 2019-01-08 10:10
You're using the API correctly, so maybe the string doesn't match up exactly, or maybe you've discovered a bug in our JavaScript utility layer.

The optional dictionary is an in-out parameter that gets populated with the actual string keys that were discovered in the filamesh, so to diagnose this issue you might want to try dumping the dictionary *after* the call:

```
const mats = {}
const filamesh = this.engine.loadFilamesh(this.filamesh_url, this.matinstance, mats);
console.log(mats);
```

Good point about the unclear documentation, I'll fix that up.

**Comment by prideout** [comment] 2019-01-08 17:11
Ah, I believe the API is not working as intended.  I'll fix this up and add a test.

**Comment by prideout** [comment] 2019-01-11 03:51
Closing after making a few commits, including a new demo that exercises this functionality. Let us know if you still have an issue.

**Closed by prideout** 2019-01-11 03:51 UTC
Labels: bug, wasm
