### ISSUE TITLE
Building Android/AAR on Windows (ninja fails)

### ISSUE THREAD

**Issue by drtyhlpr** [google/filament#711] opened 2019-01-16 15:48 UTC
**Building fine**
I followed the instructions of "Building Filament" and successfully built on "VS 2017: x64 Native Tools Command Prompt for VS 2017". Java features could also be build by setting the correct JDK paths (JAVA_HOME only complains about missing javah witch I think became javac years ago). But well all built fine. sample applications etc.

building with msbuild: **ok**
building with ninja: **ok**

**Building Android problem**
If I follow the steps of "building Filament for Android" I run into the following error:
(running VS 2017: **x64** Native Tools Command Prompt for VS 2017)
```
  The C compiler

    "C:/Users/xxx/Downloads/filament-master2/toolchains/Windows/x86_64-linux-
android-4.9/bin/x86_64-linux-android-clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/xxx/Downloads/filament-master2/out/android-build-rel
ease-x86_64/CMakeFiles/CMakeTmp

    Run Build Command:"C:/PROGRA~2/MICROS~1/2017/COMMUN~1/Common7/IDE/COMMON~1/M
ICROS~1/CMake/Ninja/ninja.exe" "cmTC_4cf8d"
    ninja: fatal: CreateProcess: %1 is not a valid Win32 application.
```

(This error exists on all tried configurations (aarch64-linux-android-4.9, arm-linux-androideabi-4.9 etc) with their corresponding cmake files)

**Ideas about the problem**
Well I tried to download and build ninja inside a "VS 2017: **x86** Native Tools Command Prompt for VS 2017" to build in win32: **no succsess**
I tried to download an available win32 version of ninja.exe: **no success** (complains about outdated in relation to cmake version)

Any ideas on how to fix that please?

ps. Wouldn't it be a great time to realease a new https://github.com/google/filament/releases last release is more than 1 month old and 49 commits behind. :-)

**Comment by romainguy** [comment] 2019-01-16 18:19
We'll have a new release soon :)

Looks like the issue is with the toolchains created by the NDK. How did you create the cross compilation toolchains?

**Comment by drtyhlpr** [comment] 2019-01-16 18:47
Hi, well not sure if it was did was right. the make_standalone_toolchain.py of the SDK created the required .exe and or .cmd files (to clang) for Windows and I "just" placed them inside toolchains\Windows.

Well strange times. I setup a debian vm with all the required deps and currently building filament (and hopefully the AAR soon) it took maybe 2h so far, I invested more time so far in the windows build tries lol.

ps. had problems to get v5+ clang on debian . found out its also possible to just use the clang bins from the ndk-bundle/toolchains/llvm/prebuilt dir +

**Comment by drtyhlpr** [comment] 2019-01-16 19:09
(aar generation - windows workaround)
install debian-netinstall-xfce, installation of deps, android studio (adding ndk), set CC and CCX to ndk-bundle/toolchains/llvm/prebuilt files. ./build | build -p android **works**

**Comment by romainguy** [comment] 2019-01-16 21:50
Did you use the following command to generate your toolchain (adapted to Windows of course)? The `--install-dir` might matter (as opposed to generating the toolchain then moving it).

```
> $SDK/ndk-bundle/build/tools/make_standalone_toolchain.py --arch arm64 --api 21 \
        --stl libc++ --force \
        --install-dir toolchains/Linux/aarch64-linux-android-4.9
```

**Comment by romainguy** [comment] 2019-01-17 17:13
@bejado Can you give this a try on Windows to see if something's broken on our side?

**Comment by bejado** [comment] 2019-01-17 20:25
I see the same issue myself- glad you were able to find a workaround. Looks like our Android toolchain file (i.e. `build/toolchain-aarch64-linux-android.cmake`) needs some modifications for it to work on Windows. I was able to cross-compile Filament for arm64 using Ninja and the NDK toolchain using these steps.

1. From Filament's root directory, run the NDK `make_standalone_toolchain.py` script:
```
python make_standalone_toolchain.py --arch arm64 --api 21 --stl libc++ --force --install-dir "toolchains/Windows/aarch64-linux-android-4.9"
````

2. Make the following modifications to `build/toolchain-aarch64-linux-android.cmake`:

```
- set(CMAKE_C_COMPILER   ${TOOLCHAIN}/bin/${ARCH}-clang)
- set(CMAKE_CXX_COMPILER ${TOOLCHAIN}/bin/${ARCH}-clang++)
+ set(CMAKE_C_COMPILER   ${TOOLCHAIN}/bin/clang80.exe)
+ set(CMAKE_CXX_COMPILER ${TOOLCHAIN}/bin/clang80++.exe)
+ set(CMAKE_AR ${TOOLCHAIN}/bin/${ARCH}-ar.exe CACHE FILEPATH "Archiver")

- set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DANDROID -fPIE -mcpu=cortex-a57" CACHE STRING "Toolchain CFLAGS")
- set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_C_FLAGS}" CACHE STRING "Toolchain CXXFLAGS")
+ set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} --target=aarch64-linux-android21")
+ set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --target=aarch64-linux-android21 -fno-addrsig -DANDROID -fPIE -mcpu=cortex-a57" CACHE STRING "Toolchain CFLAGS")
+ set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_C_FLAGS} --stdlib=libc++" CACHE STRING "Toolchain CXXFLAGS")
```

3. Create a build dir:

```
mkdir out/cmake-android-release-aarch64
cd out/cmake-android-release-aarch64
```

4. Run CMake:

```
cmake ^
    -G Ninja ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DCMAKE_INSTALL_PREFIX=..\android-release\filament ^
    -DCMAKE_TOOLCHAIN_FILE=..\..\build\toolchain-aarch64-linux-android.cmake ^
    ..\..
```

5. Build:

```
ninja install
```

This only builds the Filament static libraries- the AAR then needs to be built with Gradle. I'll dig more into it this afternoon.

**Closed** 2019-01-18 17:31 UTC
Labels: android, bug, windows

**Comment by bejado** [comment] 2019-01-18 22:48
See https://github.com/google/filament/blob/master/android/Windows.md for detailed instructions.
