### ISSUE TITLE
post-processing pass doesn't blend transparent Views

### ISSUE THREAD

**Issue by donaldmunro** [google/filament#1165] opened 2019-05-02 11:59 UTC
**Describe the bug**
My understanding of the behaviour for View::setClearTargets possibly combined with View::setRenderTarget is that it should be possible to call the Renderer::render more than once, with a different camera projection for example, without overriding the previous render. 
One use case might be  in AR to render a camera frame background using an orthographic projection, followed by one or more object renderings using perspective projection. The following code should, as I understand, allow such rendering:
~~~~
  backgroundView->setClearTargets(true, true, false);
   view->setClearTargets(false, true, false);
   view->setRenderTarget(filament::View::TargetBufferFlags::DEPTH_AND_STENCIL);
 if (renderer->beginFrame(swapChain))
   {
      renderer->render(backgroundView);
      renderer->render(view);
      renderer->endFrame();
      return true;
   }
~~~~
with backgroundView configured with a different camera and scene.

When doing this I get only the foreground view with the foreground view clearColor in the background.  Commenting out either the view or the background view render does produce the correct individual rendering. Setting View::setRenderTarget  to  DEPTH_AND_STENCIL or NONE does not seem to make a difference.

**To Reproduce**
Source code to reproduce is available at:

[https://github.com/donaldmunro/FilamentTmp](https://github.com/donaldmunro/FilamentTmp)

**Expected behavior**
The background view should not be cleared during the second call to Renderer::render. 

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Linux
 - GPU:  NVidia RTX 2070 and NVidia GeForce GTX 1060 Mobile (NVidia 418.56-10)
 - Backend: Both OpenGL and Vulkan.
![background-only](https://user-images.githubusercontent.com/427822/57073750-5bcbc380-6ce2-11e9-8091-571c81f996fd.png)
![combined](https://user-images.githubusercontent.com/427822/57073752-5bcbc380-6ce2-11e9-9596-a53a58c8bcae.png)
![foreground-only](https://user-images.githubusercontent.com/427822/57073753-5c645a00-6ce2-11e9-8933-ebf40640fbee.png)

**Comment by romainguy** [comment] 2019-05-02 16:43
We'll take a look at it but it's how we render ImGui user interfaces in our samples. Here's how the UI view is setup for instance:

```
window->mUiView->getView()->setClearTargets(false, false, false);
window->mUiView->getView()->setRenderTarget(View::TargetBufferFlags::DEPTH_AND_STENCIL);
```

**Comment by prideout** [comment] 2019-05-02 16:46
I think this is a fairly recent regression: our ImGui windows currently look a reddish instead of bluish, maybe it's blending over un-cleared pixels.

**Comment by romainguy** [comment] 2019-05-02 16:48
ImGui looks fine in `material_sandbox` for me.

**Comment by donaldmunro** [comment] 2019-05-03 10:53
Thanks. I should probably also have mentioned that I was working with the latest git HEAD from yesterday (45636e5afe84a4dbb36bbdf63097e202b5381981) and not a downloaded release.

**Comment by pixelflinger** [comment] 2019-05-06 04:51
Are you testing this with a DEBUG build?
I added debug code recently that clears target in red/yellow/green based on the discard flags to catch discard bugs. e.g. if if a buffer is discarded but not rendered later.
There could be some problem with that code. I will have a look.

**Comment by donaldmunro** [comment] 2019-05-06 10:59
Yes, I probably should have tested in release mode too. 

I'm currently getting a link error compiling in release mode (for the STL logic_error exception), although it compiles and links OK  in debug mode. I suspect its due to ArchLinux having already switched to clang 8. I have a dual boot for Ubuntu 18 at home which should still be using clang 7 and will try it there later, and/or build a clang 7 compiler.

**Comment by romainguy** [comment] 2019-05-06 18:18
We use clang 8 to build for Android so it should work.

**Comment by donaldmunro** [comment] 2019-05-07 09:48
Yes, I probably should have tested in release mode too. 

I'm currently getting a link error compiling in release mode (for the STL logic_error exception), although it compiles and links OK  in debug mode. I suspect its due to ArchLinux having already switched to clang 8. I have a dual boot for Ubuntu 18 at home which should still be using clang 7 and will try it there later, and/or build a clang 7 compiler.

**Comment by donaldmunro** [comment] 2019-05-07 10:03
I had the same link problem in Ubuntu in release mode for both clang-6 (which seems to still be their default clang) and clang-7 (which is also supported via apt install clang-7). The problem is linking libs/math/test_math (which gets linked even if the -u option to build.sh is not specified). The following link line fails:
clang++  -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -Wl,--gc-sections   -rdynamic libs/math/CMakeFiles/test_math.dir/tests/test_fast.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_mat.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_vec.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_quat.cpp.o  -o libs/math/test_math  -static-libgcc -static-libstdc++ libs/math/libmath.a third_party/libgtest/tnt/libgtest.a -static-libgcc -static-libstdc++ -pthread

However removing all the  -static-libgcc -static-libstdc++ options fixes the link:
cd out/cmake-release
clang++  -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -Wl,--gc-sections   -rdynamic libs/math/CMakeFiles/test_math.dir/tests/test_fast.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_mat.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_vec.cpp.o libs/math/CMakeFiles/test_math.dir/tests/test_quat.cpp.o  -o libs/math/test_math  libs/math/libmath.a third_party/libgtest/tnt/libgtest.a  -pthread

When I compare the output from the debug build and the release build, it does not appear to build the math test files in the debug build as far as I could see which may explain why the error does not occur in the debug build.

**Comment by pixelflinger** [comment] 2019-05-10 05:23
@donaldmunro can you try at tip of tree? -- I double checked the logic, and setClearTargets the way you're using it should work -- also could you try with different colors? (because we're using yellow/red/green for debugging, so we don't know if we're seeing your red or my red :-)).
Make sure your background view is clearing and not discarding the color buffer.

**Comment by donaldmunro** [comment] 2019-05-10 10:21
I have changed the colors:
   backgroundView->setClearTargets(true, true, false);
   view->setClearTargets(false, true, false);
   view->setRenderTarget(filament::View::TargetBufferFlags::DEPTH_AND_STENCIL);
   view->setClearColor(filament::Color::toLinear({0.8, 0.5, 0.2, 1}));
   backgroundView->setClearColor(filament::Color::toLinear({0.2, 0.5, 0.8, 1}));

I also compiled a release build by commenting out the static link in the filament main CMakeLists.txt:
# To distribute our binaries, we must remove the dependency on libc++ and libgcc.
    #    if (CMAKE_BUILD_TYPE STREQUAL "Release")
    #    link_libraries("-static-libgcc -static-libstdc++")
    #endif()

I still get a red background when using the debug libraries (first screenshot). When using the release libraries I still don't get the background texture, instead I get a black background (2nd screenshot).
![debug](https://user-images.githubusercontent.com/427822/57520329-ab7f4000-731d-11e9-8360-ad99b792f361.png)
![release](https://user-images.githubusercontent.com/427822/57520356-bd60e300-731d-11e9-8711-379ecf970879.png)

**Comment by donaldmunro** [comment] 2019-05-11 14:44
Another possibility not previously mentioned is to check whether the problem also occurs in Windows or Android, or is it Linux specific. I'll look into making the bug test code work as an Android app later. I do also have a Windows dual boot on a laptop, although I haven't used it for some time so it will probably take some time to update itself.

**Comment by donaldmunro** [comment] 2019-05-11 17:04
OK, I've got it working by adding a setPostProcessingEnabled(false):
~~~~
  backgroundView->setClearTargets(true, true, false);
   view->setClearTargets(false, true, false);
   view->setRenderTarget(filament::View::TargetBufferFlags::DEPTH_AND_STENCIL);
   view->setClearColor(filament::Color::toLinear({0.8, 0.5, 0.2, 1}));
   backgroundView->setClearColor(filament::Color::toLinear({0.2, 0.5, 0.8, 1}));
   view->setPostProcessingEnabled(false);
~~~~

based on the comment on line 410 of Renderer.cpp:
~~~~
    if (hasPostProcess) {
        // FIXME: currently we can't render a view on top of another one (with transparency) if
        //        any post-processing is performed on that view -- this is because post processing
        //        uses intermediary buffers which are not blended back (they're blitted).
~~~~

**Comment by pixelflinger** [comment] 2019-05-16 01:29
ahhhhhh right, I completely forgot about that.  Sorry for not thinking about it before.

We're not able to do a blend of views, it's always a blit right now -- so it works for views side-by-side, or without post-processing (those don't use an intermediate buffer).

How problematic is it for you? We don't have immediate plans to fix this as it hasn't been a priority for us.

**Comment by donaldmunro** [comment] 2019-05-16 13:46
I shouldn't need any fancy post processing at the moment so it shouldn't be a problem. A bit odd that it presumably works in ARCore, unless they render the camera background outside of filament using a OpenGL OES texture. Anyway thanks for the time spent on it.

**Comment by pixelflinger** [comment] 2019-05-18 21:22
@donaldmunro -- In ARCore/Sceneform the camera is rendered as a special skybox -- it's not a separate view.

**Comment by romainguy** [comment] 2019-05-20 18:05
More specifically it's just a full-screen triangle rendered with an unlit shader. You can see how we did the same thing for our skybox here: https://github.com/google/filament/blob/master/filament/src/materials/skyboxRGBM.mat

The `vertexDomain` is set to `device` so we can define the geometry in clip space (z=1 for instance).

**Comment by donaldmunro** [comment] 2019-05-20 19:28
Thanks, I'll have a look at it. I assume the cube map in rendered with only one (cube) face instead of 6 ?

**Comment by romainguy** [comment] 2019-05-20 19:29
What do you mean? We still sample from a cubemap, but we shade a single triangle.

**Comment by donaldmunro** [comment] 2019-05-20 19:40
I assumed as you presumably only have one image from the camera which you want as the front face, the rest of the faces aren't used ?

**Comment by romainguy** [comment] 2019-05-20 19:40
Ah for the camera stream it's just a regular texture, not a cubemap.

**Comment by romainguy** [comment] 2019-09-14 04:08
@pixelflinger Is this fixed with the new frame graph?

**Closed** 2019-11-19 22:05 UTC
Labels: bug
