### ISSUE TITLE
How to realize OIT(Order-independent Transparent)?

### ISSUE THREAD

**Issue by feiziang** [google/filament#3132] opened 2020-09-29 03:09 UTC
**Is your feature request related to a problem? Please describe.**
How to realize OIT with filament?
There is a bug in the rendering of crossed transparent objects
**Describe the solution you'd like**
None of the blending sets could solve the problem when translucent objects cross each other.
TwoPassOneside/TwoPassTwosides also can't work!

**OS and backend**
Is this feature OS/backend specific? If so, explain why.

**Comment by romainguy** [comment] 2020-09-29 03:09
Duplicate of issue #2838.

**Closed by romainguy** 2020-09-29 03:09 UTC
Labels: duplicate
