### ISSUE TITLE
Crash Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) in the FrameCallback

### ISSUE THREAD

**Issue by inveders** [google/filament#4168] opened 2021-06-21 15:37 UTC
**Describe the bug**
Hello, I am building an app with ARCore and Filament. Once the initialization of ARCore and Filament is done, I try to turn on the camera by doing a session.update, and I have a crash like: "Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)"
What is strange is that in debug mode, if I put a breakpoint on the session.update line, my camera turns on well after several clicks and by removing the breakpoint it remains well lit. I wonder if there is a problem with a piece of code that runs too fast? I have tried many options to solve this problem and after almost a week of research, I come to ask the question here because I have no idea where the problem can come from. If needed, I could give more code snippets to better understand the implementation.

My beginFrame is true at the beginning, when the timestamps is 0, then twice true when the timestamps is initialized, then it changes to false. So the code tries to update without rendering and it crashes. 

**Expected behavior**
Pass in the Callback frame with a begin frame to true a lot of times

**Screenshots**
````kotlin
class FrameCallback(
    private val arCore: ArCore,
    private val doFrame: (frame: Frame) -> Unit,
) : Choreographer.FrameCallback {
    companion object {
        private const val maxFramesPerSecond: Long = 60
    }

    sealed class FrameRate(val factor: Long) {
        object Full : FrameRate(1)
        object Half : FrameRate(2)
        object Third : FrameRate(3)
    }

    private val choreographer: Choreographer = Choreographer.getInstance()
    private var lastTick: Long = 0
    private var frameRate: FrameRate = FrameRate.Full

    override fun doFrame(frameTimeNanos: Long) {
        choreographer.postFrameCallback(this)
        // limit to max fps
        val nanoTime = System.nanoTime()
        val tick = nanoTime / (TimeUnit.SECONDS.toNanos(1) / maxFramesPerSecond)

        if (lastTick / frameRate.factor == tick / frameRate.factor) {
            return
        }

        lastTick = tick

        try {
            // render using frame from last tick to reduce possibility of jitter but increases latency
            arCore.filament.swapChain?.let { swapChain ->
                val beginFrame = arCore.filament.renderer.beginFrame(swapChain, frameTimeNanos)

                if (// only render if we have an ar frame
                    arCore.timestamp != 0L && arCore.filament.uiHelper.isReadyToRender && beginFrame
                ) {
                    arCore.filament.timestamp = arCore.timestamp
                    arCore.filament.renderer.render(arCore.filament.view)
                    arCore.filament.renderer.endFrame()
                }
            }

            val frame = arCore.session.update()
            // During startup the camera system may not produce actual images immediately. In
            // this common case, a frame with timestamp = 0 will be returned.
            if (frame.timestamp != 0L &&
                frame.timestamp != arCore.timestamp
            ) {
                arCore.timestamp = frame.timestamp
                arCore.update(frame, arCore.filament)
                doFrame(frame)
            }

        } catch (e: CameraNotAvailableException) {
            Log.w("debago", "Exception updating ARCore session", e)
        }

    }

    fun start() {
        choreographer.postFrameCallback(this)
    }

    fun stop() {
        choreographer.removeFrameCallback(this)
    }
}
````

**Desktop:**
 - OS: [MAC OS]
 - Framework: [Android Studio/Kotlin]
 - ArCore: 1.25.0
 - Filament: 1.10.3

**Additionnal informations**
motion_tracking_context.cc:1371] Unable to find measurements corresponding to VIO status at timestamp 
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1040 in tid 30617 (FEngine::loop), pid 28801
camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.

**Comment by romainguy** [comment] 2021-06-21 15:44
Could you share the full logs please?

**Comment by inveders** [comment] 2021-06-21 16:46
> Could you share the full logs please?

@romainguy Yes I just have these 3 lines in my error logcat (do you need the debug, info and warn lines too?):

2021-06-21 18:42:55.047 A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1040 in tid 29278 (FEngine::loop), pid 28956
2021-06-21 18:42:55.484 E/native: E0621 18:42:55.484479   29316 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 18:42:57.155 E/native: E0621 18:42:57.155549   29316 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.

**Comment by pixelflinger** [comment] 2021-06-21 17:23
Yes we'd need the full log with all the tags. Thanks.

**Comment by inveders** [comment] 2021-06-21 17:45
````
2021-06-21 19:32:59.518  I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2021-06-21 19:32:59.522  D/InputTransport: Input channel constructed: 'ClientS', fd=135
2021-06-21 19:32:59.523  D/InputTransport: Input channel destroyed: 'ClientS', fd=111
2021-06-21 19:32:59.600  **A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7fffffff7fffe7 in tid 5907 (DefaultDispatch), pid 3385**
2021-06-21 19:32:59.754  I/SurfaceControl: release : mNativeObject = 504773975776 - Surface(name=Surface(name=78fbec5 InputMethod)/@0x5efb528 - animation-leash)/@0x2d48800 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
2021-06-21 19:32:59.754  I/SurfaceControl: nativeRelease nativeObject s[504773975776]
2021-06-21 19:32:59.754  I/SurfaceControl: nativeRelease nativeObject e[504773975776]
2021-06-21 19:32:59.765  I/ViewRootImpl@2873585[SplashScreenActivity]: stopped(true) old=false
2021-06-21 19:32:59.770 I/SurfaceControl: release : mNativeObject = 506706020896 - Surface(name=....mvvm.views.activities.SplashScreenActivity$_3385)/@0x750dbc7 / android.view.ViewRootImpl.destroySurface:2497 android.view.ViewRootImpl.setWindowStopped:2345 android.view.WindowManagerGlobal.setStoppedState:741 android.app.Activity.performStop:8423 
2021-06-21 19:32:59.771  I/SurfaceControl: nativeRelease nativeObject s[506706020896]
2021-06-21 19:32:59.771  I/SurfaceControl: nativeRelease nativeObject e[506706020896]
2021-06-21 19:32:59.809  W/libEGL: EGLNativeWindowType 0x75fa0cc010 disconnect failed
2021-06-21 19:32:59.810  I/ViewRootImpl@2873585[SplashScreenActivity]: dispatchDetachedFromWindow
2021-06-21 19:32:59.823 D/InputTransport: Input channel destroyed: '873fa1 ', fd=92
2021-06-21 19:32:59.826  D/SurfaceControl: hide : mNativeObject = 506704162784 - sc.mNativeObject = 504773975968 - Surface(name=Surface(name=78fbec5 InputMethod)/@0x5efb528 - animation-leash)/@0x81d9571
2021-06-21 19:32:59.826 D/SurfaceControl: nativeSetFlags Done : Surface(name=Surface(name=78fbec5 InputMethod)/@0x5efb528 - animation-leash)/@0x81d9571
2021-06-21 19:32:59.829  I/SurfaceControl: release : mNativeObject = 505096183296 - Surface(name=Surface(name=a2c8eb2 NavigationBar0)/@0xdb78ec - animation-leash)/@0x5d135ed / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-06-21 19:32:59.829 I/SurfaceControl: nativeRelease nativeObject s[505096183296]
2021-06-21 19:32:59.829 I/SurfaceControl: nativeRelease nativeObject e[505096183296]
2021-06-21 19:32:59.846 I/native: I0621 19:32:59.846396    3385 session.cc:3293] Update Frame Delay to 0 frames.
2021-06-21 19:33:00.532  I/native: I0621 19:33:00.532517    6497 logger.h:28] DataSourceMetrics: kFirstGlCallback: 1.72482823s
2021-06-21 19:33:00.569  I/native: I0621 19:33:00.569445    6496 timebase_helpers.cc:170] Timebase offset intialized to 0
2021-06-21 19:33:00.577  I/native: I0621 19:33:00.576863    6498 logger.h:28] CameraMetrics: FirstCaptureComplete: 1.212825269s
2021-06-21 19:33:00.577  I/native: I0621 19:33:00.577415    6496 logger.h:28] DataSourceMetrics: kFirstImageCallback: 1.769743383s
2021-06-21 19:33:00.641  I/CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client ... API Level 2
2021-06-21 19:33:00.651 I/native: I0621 19:33:00.650930    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:00.655 W/native: W0621 19:33:00.655771    6481 feature_matcher_and_filter_utils.cc:260] INVALID_ARGUMENT: integration window start at 0 Use identity R.
2021-06-21 19:33:00.792  E/native: E0621 19:33:00.792004    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:00.853  I/native: I0621 19:33:00.852958    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:00.856  E/native: E0621 19:33:00.856303    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:00.868  E/native: E0621 19:33:00.868443    6484 motion_tracking_context.cc:1371] Unable to find measurements corresponding to VIO status at timestamp 153175580265809.
2021-06-21 19:33:00.932  I/native: I0621 19:33:00.931298    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:00.989 E/native: E0621 19:33:00.989004    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:01.067  I/SurfaceView: surfaceChanged (1080,1920) 1 #5 android.view.SurfaceView{571fb0e V.E...... ......ID 0,210-1080,2130 #7f0a0210 app:id/surface_view}
2021-06-21 19:33:01.070  I/native: I0621 19:33:01.070397    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.083 I/ViewRootImpl@5038d09[MainActivity]: [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1311 android.view.SurfaceView.setFrame:646 android.view.View.layout:24472 
2021-06-21 19:33:01.091  I/ViewRootImpl@5038d09[MainActivity]: [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:577 android.view.SurfaceView.performDrawFinished:564 android.view.SurfaceView.lambda$TWz4D2u33ZlAmRtgKzbqqDue3iM:0 
2021-06-21 19:33:01.091  I/ViewRootImpl@5038d09[MainActivity]: [DP] rdf()
2021-06-21 19:33:01.115  I/native: I0621 19:33:01.115698    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.127  I/SurfaceView: setParentSpaceRectangle: useBLAST = false position = Rect(0, 210 - 1080, 2130) frameNumber = 4 t = android.view.SurfaceControl$Transaction@ae74017
2021-06-21 19:33:01.128  I/SurfaceView: applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@ae74017 surfaceControl = Surface(name=SurfaceView - ...mvvm.views.activities.MainActivity@571fb0e@0)/@0x2c77c04 frame = 4
2021-06-21 19:33:01.131  I/SurfaceView: applySurfaceTransforms: postScaleX = 1.0 postScaleY = 1.0
2021-06-21 19:33:01.136  I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
2021-06-21 19:33:01.258 I/native: I0621 19:33:01.258175    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.313  I/native: I0621 19:33:01.313384    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.420  E/native: E0621 19:33:01.420636    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:01.464 I/native: I0621 19:33:01.464229    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.556  I/native: I0621 19:33:01.556747    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.616 E/native: E0621 19:33:01.616505    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:01.675  I/native: I0621 19:33:01.675505    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.690  E/native: E0621 19:33:01.690051    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:01.766  I/native: I0621 19:33:01.765934    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.767  I/native: I0621 19:33:01.766671    6457 performance_monitor.cc:115] Event: FeatureExtraction is taking too long, it took 115.542ms
2021-06-21 19:33:01.859  I/native: I0621 19:33:01.859836    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:01.961  I/native: I0621 19:33:01.961667    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.073 I/native: I0621 19:33:02.073395    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.079 E/native: E0621 19:33:02.078826    6484 motion_tracking_context.cc:1371] Unable to find measurements corresponding to VIO status at timestamp 153176813211193.
2021-06-21 19:33:02.160  I/native: I0621 19:33:02.160056    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.270 I/native: I0621 19:33:02.270549    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.295 E/native: E0621 19:33:02.294803    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:02.371  I/native: I0621 19:33:02.370884    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.467 I/native: I0621 19:33:02.467089    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.571 I/native: I0621 19:33:02.571196    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.677  I/native: I0621 19:33:02.676969    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.681  I/SurfaceControl: release : mNativeObject = 504773975968 - Surface(name=Surface(name=78fbec5 InputMethod)/@0x5efb528 - animation-leash)/@0x81d9571 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
2021-06-21 19:33:02.681 I/SurfaceControl: nativeRelease nativeObject s[504773975968]
2021-06-21 19:33:02.681 I/SurfaceControl: nativeRelease nativeObject e[504773975968]
2021-06-21 19:33:02.681  I/SurfaceControl: release : mNativeObject = 504773975872 - Surface(name=Surface(name=a2c8eb2 NavigationBar0)/@0xdb78ec - animation-leash)/@0xa19f130 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
2021-06-21 19:33:02.681  I/SurfaceControl: nativeRelease nativeObject s[504773975872]
2021-06-21 19:33:02.682  I/SurfaceControl: nativeRelease nativeObject e[504773975872]
2021-06-21 19:33:02.740  I/native: I0621 19:33:02.740295    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.817 E/native: E0621 19:33:02.817523    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:02.842  I/native: I0621 19:33:02.842300    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.965 I/native: I0621 19:33:02.965715    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:02.986 E/native: E0621 19:33:02.986299    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:03.043  I/native: I0621 19:33:03.043332    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:03.164 I/native: I0621 19:33:03.164745    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:03.181 E/native: E0621 19:33:03.181516    6496 camera_image_stream.cc:271] FAILED_PRECONDITION: Failed to extract the native metadata, status=DEADLINE_EXCEEDED: Timed out waiting for metadata.
2021-06-21 19:33:03.259  I/native: I0621 19:33:03.259728    6457 distribute.cc:79] No keypoints to prune.
2021-06-21 19:33:03.356 I/native: I0621 19:33:03.356344    6457 distribute.cc:79] No keypoints to prune.
````

**Comment by pixelflinger** [comment] 2021-06-23 05:44
The fault address is very suspicious ( fault addr 0x7fffffff7fffe7), that looks like some code is calling an invalid function pointer, maybe an invalid virtual function or something like that. That's very odd.
It definitely smells like a race condition, where some code is calling through a function pointer that is not yet ready.

Is there any way you could send us an APK that reproduces the problem?

**Comment by inveders** [comment] 2021-06-23 10:22
yes @pixelflinger can I have your email address please?

**Comment by pixelflinger** [comment] 2021-06-25 19:27
I have reproduced the problem with the sample app, but wasn't able to get more debug info. I will need to try to use a debug version of filament. Hopefully next week.

**Comment by RGregat** [comment] 2021-07-06 05:01
I'm just an interested reader on this issue :)
Are there any updates or further investigations on this issue?

**Comment by pixelflinger** [comment] 2021-07-06 18:16
Not yet. We're not forgetting about it, just a lot of other things to do.

**Comment by pixelflinger** [comment] 2021-07-12 19:22
The root of the problem here is that filament is called from the wrong thread. 

Filament must *only* be called from the thread that created the Filament Engine. When using a debug version of filament, there are a few extra checks that verify certain commands are not called from another thread:
```
E/Filament: in void utils::panic(const char *, const char *, int, const char *):32
    in file ../../libs/utils/src/debug.cpp
    reason: ../../filament/backend/include/private/backend/CommandStream.h:316: failed assertion `mThreadId == std::this_thread::get_id()'
```
I have not been able to get a symbolized stack trace though.

**Comment by pixelflinger** [comment] 2021-07-12 23:10
Closing since it is not a filament bug.

**Closed by pixelflinger** 2021-07-12 23:10 UTC
Labels: android, bug
