### ISSUE TITLE
Desktop rendering has Z-fighting when depth prepass is enabled

### ISSUE THREAD

**Issue by AdrianAtGoogle** [google/filament#293] opened 2018-09-21 21:25 UTC
**Describe the bug**
On Desktop, GL seems to compute slightly different clip-space values for triangles between depth prepass and normal render.  This means that when the normal render (using `GL_LEQUAL`) runs, some fragments incorrectly compute a depth slightly behind what is found in the zbuffer and they are culled, leaving holes in the image.

Does NOT repro in GLES (via swiftshader)

Does NOT repro with depth prepass disabled.

**To Reproduce**
This repros even with absurdly close depth planes (attached screenshot, object is ~3wu away from the camera and the depth range fed to setProjection is (2.5, 3)

**Screenshots**
![artifacts](https://user-images.githubusercontent.com/26070065/45906668-d9713d80-bda9-11e8-9874-61ac8db5fc64.png)

**Desktop (please complete the following information):**
 - OS: linux
 - GPU: nVidia Quadro M2000
 - Backend: OpenGL

**Comment by romainguy** [comment] 2018-09-21 21:29
We've seen this issue happen on Linux in the past, it doesn't repro on Windows nor macOS. We are using `invariant gl_Position` precisely to avoid this issue. What drivers are you using?

**Comment by AdrianAtGoogle** [comment] 2018-09-21 21:43
(hope I did this right)
```
$ apt policy xserver-xorg-video-nvidia
xserver-xorg-video-nvidia:
  Installed: 384.111-3
  Candidate: 384.111-3
  Version table:
     384.130-1 600
        600 https://xxxxxxx/main amd64 Packages
 *** 384.111-3 9990
       1500 https://xxxxxxx/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by romainguy** [comment] 2018-09-21 23:40
Thanks, could you attach the model as well please so we can repro? Or does this happen with any model?

@prideout Could you take a look next week please?

**Comment by prideout** [comment] 2018-09-21 23:57
Will do.

**Comment by AdrianAtGoogle** [comment] 2018-09-24 17:39
Model: Nvidia GM206GL [Quadro M2000]

**Comment by prideout** [comment] 2018-09-24 18:36
Adrian gave me some pointers offline and I am able to repro with the sushi model on a Quadro M4000 with 384.111.

I had a theory that the invariant qualifier was getting dropped by shader optimization, but it seems to occur regardless of the opt level.

**Comment by prideout** [comment] 2018-09-24 23:43
For the depth pass, we always pass `depth_main.vs` straight to GL, no optimizations:

    gl_Position = getClipFromWorldMatrix() * material.worldPosition;

For the color pass, we have the same line in `main.vs`. However the the asset has optimized shaders, so the finalized GLSL looks like:

    vec4 _712 = (objectUniforms.worldFromModelMatrix[0] * _650.x) + ((objectUniforms.worldFromModelMatrix[1] * _650.y) + ((objectUniforms.worldFromModelMatrix[2] * _650.z) + objectUniforms.worldFromModelMatrix[3]));
    gl_Position = frameUniforms.clipFromWorldMatrix * _712;
    
The variance arises because prepass depth and colorpass depth are not computed in exactly the same way.

The issue goes away when hacking `depth_main.vs` by replacing `material.worldPosition` with a direct call to `computeWorldPosition()`.

**Comment by romainguy** [comment] 2018-09-25 00:14
We should try to optimize depth_main. I'm surprised it's not actually.

**Comment by prideout** [comment] 2018-09-25 17:01
Normally it is optimized but this particular build of Filament is not built with CMake. I've confirmed that this fixes the problem, following up with Adrian offline.

**Comment by prideout** [comment] 2018-09-27 05:09
Adrian has informed me that this worked, closing.

**Closed by prideout** 2018-09-27 05:09 UTC
Labels: bug, linux

**Comment by shartte** [comment] 2018-11-29 11:32
I can also confirm that this happens for me with filament on Windows.
Once I passed `-O` to matc for compiling my own materials, this issue disappeared.
Just a note: I built filament with CMake in debug mode, and compiled my own materials without `-O` and this issue occured, so other people might run into this when they build their own versions.

**Comment by romainguy** [comment] 2018-11-29 17:13
Right, filament and its materials must be compiled with the same optimization level at the moment.
