### ISSUE TITLE
iOS 17 Transparency rendering exception

### ISSUE THREAD

**Issue by Rankilau** [google/filament#7185] opened 2023-09-19 06:43 UTC
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
iOS 17 When filament renders a shadow material and the shadow image has transparency, an abnormal display occurs. But it did not happen before iOS17

**To Reproduce**
1. Custom shadow.inc with transparency
 
2.   _mMaterial = Material::Builder()
        .package((void*)SHADOW_COLOR_PACKAGE, sizeof(SHADOW_COLOR_PACKAGE))
        .build(*engine);
    _mMaterailInstance = _mMaterial->createInstance();
    const TextureSampler &shadowSampler = TextureSampler();
    _mMaterailInstance->setParameter("texture", _mCameraTexture, shadowSampler);

**Expected behavior**
   Materials with transparency also display normally

**Screenshots**
![shadow](https://github.com/google/filament/assets/9720783/1a55c277-0a40-4776-a0e8-4289d9b08c9b)
![wecom-temp-63860-39b692783daf9dcd4721e83beea59774](https://github.com/google/filament/assets/9720783/bb1e2f20-812e-4461-b9ef-672d3ae579c3)

[shadow.mat.zip](https://github.com/google/filament/files/12656654/shadow.mat.zip)

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by pixelflinger** [comment] 2023-09-22 16:46
what does it mean "the shadow image has transparency" ? Can you provide a gltf file showing the problem?

**Comment by bejado** [comment] 2023-10-25 19:36
Closing due to lack of information/inability to reproduce. If this is still a valid issue, please provide a patch we can apply to one of our iOS samples to reproduce the issue.

**Closed by bejado** 2023-10-25 19:36 UTC
Labels: bug, ios
