### ISSUE TITLE
Random crash on some android 9.0 

### ISSUE THREAD

**Issue by geroge-d** [google/filament#1864] opened 2019-11-09 11:38 UTC
We met some random crash on android 9.0 device. It seams in the method CommandBufferQueue::flush(), caused by    assert(used <= mFreeSpace);
The stacktrace below:

1 #00 pc 00000000000223bc /system/lib64/libc.so (abort+116) [arm64-v8a]
--
2 #01 pc 0000000000022734 /system/lib64/libc.so (__assert2+52) [arm64-v8a]
3 #02 pc 00000000002cc868 /data/app/-BikToprfQ6eAxFRmMrnjZg==/lib/arm64/libfilament-jni.so (filament::backend::CommandBufferQueue::flush()+440) [arm64-v8a]
4 #03 pc 00000000001e4e6c /data/app/com.kaiqi.videoae-BikToprfQ6eAxFRmMrnjZg==/lib/arm64/libfilament-jni.so (filament::details::FEngine::flushCommandBuffer(filament::backend::CommandBufferQueue&)+44) [arm64-v8a]
5 #04 pc 00000000001e537c /data/app/com.kaiqi.videoae-BikToprfQ6eAxFRmMrnjZg==/lib/arm64/libfilament-jni.so (filament::details::FEngine::flush()+28) [arm64-v8a]
6 #05 pc 0000000000289e80 /data/app/com.kaiqi.videoae-BikToprfQ6eAxFRmMrnjZg==/lib/arm64/libfilament-jni.so (filament::FrameGraph::execute(filament::details::FEngine&, filament::backend::CommandStream&)+224) [arm64-v8a]
7 #06 pc 0000000000241cb8 /data/app/com.kaiqi.videoae-BikToprfQ6eAxFRmMrnjZg==/lib/arm64/libfilament-jni.so (filament::details::FRenderer::renderJob(utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Debug> >&, filament::details::FView&)+2584) [arm64-v8a]
8 #07 pc 0000000000241228 /data/app/com.kaiqi.videoae-BikToprfQ6eAxFRmMrnjZg==/lib/arm64/libfilament-jni.so (filament::details::FRenderer::render(filament::details::FView const*)+376) [arm64-v8a]
9 #08 pc 0000000000242e1c /data/app/com.kaiqi.videoae-BikToprfQ6eAxFRmMrnjZg==/lib/arm64/libfilament-jni.so (filament::Renderer::render(filament::View const*)+60) [arm64-v8a]
10 #09 pc 00000000001b04a4 /data/app/com.kaiqi.videoae-BikToprfQ6eAxFRmMrnjZg==/lib/arm64/libfilament-jni.so (Java_com_google_android_filament_Renderer_nRender+52) [arm64-v8a]
11 #10 pc 000000000053c7e0 /system/lib64/libart.so (art::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::CalleeSaveType const&)+168) [arm64-v8a]
12 #11 pc 0000000000533a4c /system/lib64/libart.so (art::Monitor::LogContentionEvent(art::Thread*, unsigned int, unsigned int, art::ArtMethod*, unsigned int)+560) [arm64-v8a]
13 #12 pc 00000000000a92e8 /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232) [arm64-v8a]
14 #13 pc 000000000025a16c /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344) [arm64-v8a]
15 #14 pc 0000000000254174 /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968) [arm64-v8a]
16 #15 pc 0000000000504310 /system/lib64/libart.so (MterpInvokeStatic+204) [arm64-v8a]
17 #16 pc 0000000000525f94 /system/lib64/libart.so (ExecuteMterpImpl+14612) [arm64-v8a]
18 #17 pc 0000007ab03e23ec <unknown>
19 java:
20 com.google.android.filament.Renderer.a(Unknown Source:8)

**Comment by geroge-d** [comment] 2019-11-09 11:39
We use the latest version  1.42 of Filament

**Comment by roxlu** [comment] 2020-01-21 12:57
Running into a similar issue with scene that holds about 3500 objects;  most of them instances of the same mesh data

```
/src/fila/filament/backend/src/CommandBufferQueue.cpp:75: void filament::backend::CommandBufferQueue::flush(): Assertion `used <= mFreeSpace' failed.

Thread 1 "test-filarsf-de" received signal SIGABRT, Aborted.
0x00007ffff616bf25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff616bf25 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6155897 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6155767 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff6164526 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000055555625e92a in filament::backend::CommandBufferQueue::flush (this=0x7fffee6c2830)
    at /home/roxlu/filament/build/build_unix.Debug/fila-prefix/src/fila/filament/backend/src/CommandBufferQueue.cpp:75
#5  0x00005555561005bb in filament::details::FEngine::flushCommandBuffer (this=0x7fffee6c2010, commandQueue=...)
    at /home/roxlu/filament/build/build_unix.Debug/fila-prefix/src/fila/filament/src/Engine.cpp:493
#6  0x0000555556100a05 in filament::details::FEngine::flush (this=0x7fffee6c2010)
    at /home/roxlu/filament/build/build_unix.Debug/fila-prefix/src/fila/filament/src/Engine.cpp:390
#7  0x00005555561983e9 in filament::FrameGraph::execute (this=0x7fffffffcc28, engine=..., driver=...)
    at /home/roxlu/filament/build/build_unix.Debug/fila-prefix/src/fila/filament/src/fg/FrameGraph.cpp:656
#8  0x000055555614f4ac in filament::details::FRenderer::renderJob (this=0x55555759ea30, arena=..., view=...)
    at /home/roxlu/filament/build/build_unix.Debug/fila-prefix/src/fila/filament/src/Renderer.cpp:435
#9  0x000055555614e456 in filament::details::FRenderer::render (this=0x55555759ea30, view=0x555558542810)
    at /home/roxlu/filament/build/build_unix.Debug/fila-prefix/src/fila/filament/src/Renderer.cpp:174
#10 0x0000555556150412 in filament::Renderer::render (this=0x55555759ea30, view=0x555558542810)
```

**Comment by romainguy** [comment] 2020-04-09 16:48
This will be solved when we add a way to increase the size of the command queue. @pixelflinger

**Comment by pixelflinger** [comment] 2021-07-07 17:37
duplicate of issue #2057
https://github.com/google/filament/issues/2057

**Closed by pixelflinger** 2021-07-07 17:37 UTC
Labels: android, bug
