### ISSUE TITLE
Artifacts on 1.20.0+

### ISSUE THREAD

**Issue by ignatmsq** [google/filament#6428] opened 2023-01-05 09:07 UTC
**Describe the bug**
UI artifacts in model (please, see screenshot).
Tested with sample projects according to article (https://medium.com/@philiprideout/getting-started-with-filament-on-android-d10b16f0ec67)

**To Reproduce**
1. Prepare app according to article mentioned. above
2. Load model

**Expected behavior**
No artifacts in UI for model

**Screenshots**
![photo_2023-01-05 12 01 54](https://user-images.githubusercontent.com/43048099/210741637-dd4c3e9c-b15f-4a7b-baba-95bdd9f2bdcd.jpeg)

**Logs**
No logs

**Desktop (please complete the following information):**
- Mobile issue

**Smartphone (please complete the following information):**
 - Device: Samsun Galaxy s8+, Pixel 2 XL (emulator)
 - OS: Android 8.0, Android 12.0

**Additional context**
-

**Comment by romainguy** [comment] 2023-01-05 16:26
Can you please share the model you are using?

**Comment by ignatmsq** [comment] 2023-01-05 18:05
Thank you for your quick response.
Please, see attached

**Comment by ignatmsq** [comment] 2023-01-05 18:05
If needed I can share my sample project too.

**Comment by romainguy** [comment] 2023-01-05 18:06
You forgot to add the file it seems?

**Comment by ignatmsq** [comment] 2023-01-05 18:18
It is attached to my first email.
Please, try download from drive:
https://drive.google.com/file/d/1SQVsy3wpHBcHbbeuox0zkHXUI5vanlfW

**Comment by romainguy** [comment] 2023-01-06 02:05
The model itself is broken. It fails in other glTF viewers as well (like https://gltf-viewer.donmccurdy.com/). The problem is that the model is marked as transparent ("BLEND" in glTF), which cannot guarantee the rendering order of the triangles.

**Closed by romainguy** 2023-01-06 02:05 UTC
