### ISSUE TITLE
C2678 Error when build filament v1.9.2

### ISSUE THREAD

**Issue by 1939938853** [google/filament#3327] opened 2020-12-01 20:20 UTC
Hello,

I was trying to build  filament v1.9.2 with Visual Studio 2019 on Windows 10,  but got the following errors.

Can anyone help me to figure out what is the problem?

Thank you!
![Capture](https://user-images.githubusercontent.com/59957922/100792487-ffc7a480-341a-11eb-94ec-2b2993a79abb.JPG)

**Comment by romainguy** [comment] 2020-12-01 20:29
Duplicate of #3324

We've been experiencing build errors on Windows lately, we're trying to gix them.

**Closed by romainguy** 2020-12-01 20:29 UTC
