### ISSUE TITLE
App is crashing because of modelViewer.loadModelGlb()

### ISSUE THREAD

**Issue by Yuan-Chang** [google/filament#7024] opened 2023-08-01 22:50 UTC
**Describe the bug**
1. The ModelViewer loadModelGlb(), loadModelGltf(), loadModelGltfAsync functions are causing crash when the fragment or activity got destroyed in a short time.

2. The crash doesn't happen if we destroy the activity after 2 seconds the loadModelGlb() is called.

3. Verified that this issue doesn't happen on filament version 1.20.2 and 1.38.0

4. This crash is reproducible everytime

**To Reproduce**
Here is a sample app to reproduce this issue
[[git@github.com:Yuan-Chang/FilamentCrash.git](https://github.com/Yuan-Chang/FilamentCrash)](https://github.com/Yuan-Chang/FilamentCrash)

1. Open the app
2. Click on next button to launch the second activity which is calling loadModelGlb in onCreate()
3. Quickly press back button or using "swiping back" gesture to go back to the first activity (**Stay in the page longer than 2 seconds won't see the crash**)
5. The app crash (See crash log below)

**Expected behavior**
The app shouldn't crash

**Logs**
08-01 15:00:58.437 11816 11816 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
08-01 15:00:58.437 11816 11816 F DEBUG   :     x0  0000000000000000  x1  0000000000002d9b  x2  0000000000000006  x3  0000007fd7cbac50
08-01 15:00:58.437 11816 11816 F DEBUG   :     x4  b400006d5eeee201  x5  b400006d5eeee201  x6  b400006d5eeee201  x7  676e696d6f636562
08-01 15:00:58.437 11816 11816 F DEBUG   :     x8  00000000000000f0  x9  0000006fe0ddebf8  x10 0000000000000001  x11 0000006fe0e1f830
08-01 15:00:58.437 11816 11816 F DEBUG   :     x12 0000000000007686  x13 000000007fffffff  x14 0000000025198914  x15 00002c55749b7c27
08-01 15:00:58.437 11816 11816 F DEBUG   :     x16 0000006fe0e87d70  x17 0000006fe0e63570  x18 000000701b73a000  x19 0000000000002d9b
08-01 15:00:58.437 11816 11816 F DEBUG   :     x20 0000000000002d9b  x21 00000000ffffffff  x22 b400006e5ef26dc8  x23 b400006e3ef54e18
08-01 15:00:58.437 11816 11816 F DEBUG   :     x24 b400006e3ef55200  x25 b400006cfeeea0f0  x26 0000007fd7cbb01c  x27 0000007fd7cbb010
08-01 15:00:58.437 11816 11816 F DEBUG   :     x28 0000007fd7cbaf10  x29 0000007fd7cbacd0
08-01 15:00:58.437 11816 11816 F DEBUG   :     lr  0000006fe0e10768  sp  0000007fd7cbac30  pc  0000006fe0e10794  pst 0000000000001000
08-01 15:00:58.437 11816 11816 F DEBUG   : backtrace:
08-01 15:00:58.437 11816 11816 F DEBUG   :       #00 pc 0000000000053794  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 5111da12b6134a422c2730af0cf237cb)
08-01 15:00:58.437 11816 11816 F DEBUG   :       #01 pc 000000000013dae8  /data/app/~~_ywBnnttWT_xhjveqel6GQ==/com.sample.myapplication-6aFc4Lxjttaf51eSRtAZSA==/base.apk!libfilament-jni.so (BuildId: 6365426538456b5ea8cb0edddfb1a86a86832c6a)

**Desktop (please complete the following information):**
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
Samsung S22 Ultra

**Additional context**
This crash doesn't seem to happen if the activity doesn't get destroyed after 2 seconds the loadModelGlb() is called.

**Comment by victorbrndls** [comment] 2023-08-02 00:13
I've been able to reproduce the same problem using Filament 1.40.0

**Comment by pixelflinger** [comment] 2023-08-02 17:43
looks like a duplicate of #6933 indeed

**Closed by pixelflinger** 2023-08-02 17:43 UTC
Labels: duplicate
