### ISSUE TITLE
Non-fatal panic terminates in release builds [on Desktop/iOS but not on Android/Web]?

### ISSUE THREAD

**Issue by alexey-pelykh** [google/filament#3585] opened 2021-02-26 12:10 UTC
Due to
https://github.com/google/filament/blob/f1fd96983b0074c082f21f0ecbc6356005619fd0/libs/utils/include/utils/Panic.h#L26
this being true if the compiler supports exceptions 
https://github.com/google/filament/blob/f1fd96983b0074c082f21f0ecbc6356005619fd0/libs/utils/include/utils/Panic.h#L474
is always resolved to `PANIC_PRECONDITION` instead of `PANIC_LOG`

Is that expected behavior?

cc @romainguy

**Comment by romainguy** [comment] 2021-02-26 17:22
I believed this is the expected behavior when exceptions are supported yes. Note that this happens only in debug builds.

**Comment by alexey-pelykh** [comment] 2021-02-26 17:32
But in release build `UTILS_EXCEPTIONS` is also defined, so we're getting `1 || 0`, so true anyways, or I'm missing something?

**Comment by romainguy** [comment] 2021-02-26 17:39
No you're right, I shouldn't read code first thing in the morning ^^ @pixelflinger can give more info about the exceptions vs non-exceptions behavior.

**Comment by pixelflinger** [comment] 2021-02-26 20:04
Hi -- so conceptually, filament uses exceptions to report programming errors such as preconditions violations and postconditions violations such as running out of memory. Note that preconditions errors should never happen, they reflect a misuse of the APIs and postconditions errors should be very rare and only happen in situations where all is lost (e.g. failed allocation of a small object -- we won't panic when allocating large buffers for instance).

The idea behind using exceptions is that:
1) we didn't want to have APIs that return errors for cases that are misuses of the API.
2) we wanted to decouple the detection of an error and the "what to do with it". 
3) we didn't want to systematically abort() because filament could be used in an application where user data could be lost if filament just abort()ed. In other words, we wanted to give the app a chance to at least save user data.

Now, there are many applications that, for various reasons, can't use exceptions. In that case, instead of throwing, we log a message and abort().

By default, we do not enable exceptions on **ANDROID** and **WEBGL** *release* builds, due to code size constraints, but we do in all other builds.

**Comment by alexey-pelykh** [comment] 2021-02-26 20:10
If I got that right, desktop and iOS builds would crash on non-fatal precondition in release builds?

Just curious, would it be worth adding either some details to those conditions and/or add a separate flag that governs the behavior instead of relying on presence of exceptions support?

It was quite unexpected to figure out that simple setting of material parameter that may or may not exist (non-fatal for sure) would not crash release android but would crash release desktop

**Comment by pixelflinger** [comment] 2021-02-27 06:38
Actually the fact that we don't turn off exceptions on iOS is an oversight, I believe.

The thing is, setting a non existing parameter on a material is a misuse of the API, it is a programming error that should be fixed. This check is here only to help you, the programmer, do debug your code -- you should treat it as an assert. Maybe it was a mistake to introduce the concept of non-fatal asserts.

Now, we are defining the API, and for that specific case, we could decide that, as part of the API, setting a non existant parameter is ok, and not an error. I see this as a separate discussion.

I think we could indeed control the behavior from a compilation flag instead of exceptions. Still, in think the best solution is to fix those errors.

**Comment by romainguy** [comment] 2021-02-27 06:41
Note that we provide an API to check if a material parameter exists.

**Comment by alexey-pelykh** [comment] 2021-02-27 09:51
@romainguy yep, it was just an example when API behaviour across platforms is inconsistent. Yet purely IMHO: setting non-existent parameter is not good, but not fatal, unless it's some strict mode of operation enabled.

@pixelflinger thanks for explanation!

**Comment by pixelflinger** [comment] 2022-08-16 20:09
I think this became moot recently because we changed all non fatal asserts in public APIs to fatal ones.

**Closed by pixelflinger** 2022-08-16 20:09 UTC
Labels: enhancement
