### ISSUE TITLE
build.sh failing with default member initializer  error.

### ISSUE THREAD

**Issue by chandusam2002** [google/filament#1294] opened 2019-06-13 17:22 UTC
**Describe the bug**
[107/272] Building CXX object filament/CMakeFiles/filament.dir/src/DFG.cpp.o
FAILED: filament/CMakeFiles/filament.dir/src/DFG.cpp.o 
/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_SUPPORTS_METAL -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -I../../libs/geometry/include -I../../libs/filaflat/include -I../../libs/filabridge/include -I../../third_party/smol-v/tnt/../source -I../../libs/image/include -I../../libs/bluegl/include -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -isysroot Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk   -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility=hidden -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/CMakeFiles/filament.dir/src/DFG.cpp.o -MF filament/CMakeFiles/filament.dir/src/DFG.cpp.o.d -o filament/CMakeFiles/filament.dir/src/DFG.cpp.o -c ../../filament/src/DFG.cpp
In file included from ../../filament/src/DFG.cpp:19:
In file included from ../../filament/src/details/Engine.h:21:
In file included from ../../filament/src/PostProcessManager.h:24:
../../filament/src/fg/FrameGraphResource.h:102:9: error: default member initializer for 'mHandle' needed within definition of enclosing class 'Attachments' outside of member functions
        AttachmentInfo() noexcept = default;
        ^
../../filament/src/fg/FrameGraphResource.h:125:43: note: in instantiation of template class 'std::__1::array<filament::FrameGraphRenderTarget::Attachments::AttachmentInfo, 2>' requested here
        std::array<AttachmentInfo, COUNT> textures = {};
                                          ^
../../filament/src/fg/FrameGraphResource.h:117:28: note: default member initializer declared here
        FrameGraphResource mHandle{};
                           ^
../../filament/src/fg/FrameGraphResource.h:102:9: error: default member initializer for 'mLevel' needed within definition of enclosing class 'Attachments' outside of member functions
        AttachmentInfo() noexcept = default;
        ^
../../filament/src/fg/FrameGraphResource.h:118:17: note: default member initializer declared here
        uint8_t mLevel = 0;
                ^
../../filament/src/fg/FrameGraphResource.h:102:9: error: default member initializer for 'mAccess' needed within definition of enclosing class 'Attachments' outside of member functions
        AttachmentInfo() noexcept = default;
        ^

**To Reproduce**
1. Run ./build.sh release

**Expected behavior**
build.sh is successful

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5

**Additional context**
cmake version 3.14.5
ninja version 1.9.0
xcode version 9.2

**Comment by romainguy** [comment] 2019-06-13 17:26
Thank you. What does `clang --version` outputs on your machine? I'm on cmake 3.14.4, macOS 10.14.5 but I use Xcode 10 and I cannot reproduce the issue.

**Comment by romainguy** [comment] 2019-06-13 17:30
@pixelflinger I took a quick look and I don't understand the error. A quick search shows that it seems to be a clang/gcc bug in some versions of the compiler.

@chandusam2002 Any chance you can update Xcode?

**Comment by chandusam2002** [comment] 2019-06-13 17:57
@romainguy / @pixelflinger I have upgraded to xcode version 10.2.1 and it did resolve the issue. Thank you very much for the quick response. Shall i close the issue or leave it as open?

**Comment by romainguy** [comment] 2019-06-13 17:58
Thanks! I'll close the issue since there's an easy fix. Unless someone runs into the problem and can't upgrade Xcode I'd rather not do anything :)

**Closed by romainguy** 2019-06-13 17:58 UTC
