### ISSUE TITLE
Crashed on targetSdkVersion=29 with Pixel QPP4.190502.019

### ISSUE THREAD

**Issue by Markcz** [google/filament#1345] opened 2019-06-25 10:27 UTC
**Describe the bug**
Crashed on targetSdkVersion=29, but normal on targetSdkVersion=28 .

**Smartphone (please complete the following information):**
 - Device: [Pixel]
 - OS: [e.g. Android Q 10 QPP4.190502.019]

**Log**
    E/Filament: Panic
    in void *filament::CircularBuffer::alloc(size_t):124
    reason: couldn't allocate 6144 KiB of memory for the command buffer 
--------- beginning of system
2019-06-25 18:15:31.882 12606-12606/? E/Filament: Panic
    in void *filament::CircularBuffer::alloc(size_t):124
    reason: couldn't allocate 6144 KiB of memory for the command buffer
2019-06-25 18:15:31.882 12606-12606/? E/Filament: --------- beginning of crash
2019-06-25 18:15:31.883 12606-12606/? A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12606 (asure.altimeter), pid 12606 (asure.altimeter)
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG: Build fingerprint: 'google/sailfish/sailfish:10/QPP4.190502.019/5642755:user/release-keys'
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG: Revision: '0'
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG: ABI: 'arm64'
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG: Timestamp: 2019-06-25 18:15:31+0800
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG: pid: 12606, tid: 12606, name: asure.altimeter  >>> com.xinmang.camera.measure.altimeter <<<
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG: uid: 0
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG:     x0  0000000000000000  x1  000000000000313e  x2  0000000000000006  x3  0000007ffcecef10
2019-06-25 18:15:31.953 12797-12797/? A/DEBUG:     x4  4a634d1a1e113100  x5  4a634d1a1e113100  x6  4a634d1a1e113100  x7  8031111e1a4d634a
2019-06-25 18:15:31.954 12797-12797/? A/DEBUG:     x8  00000000000000f0  x9  d094db62403fe51f  x10 fffffff0fffffbdf  x11 0000000000000000
2019-06-25 18:15:31.954 12797-12797/? A/DEBUG:     x12 0000000000000000  x13 0000000000000005  x14 0000000000000001  x15 4a634d1a1e113100
2019-06-25 18:15:31.954 12797-12797/? A/DEBUG:     x16 0000007405f3a8b8  x17 0000007405f18710  x18 0000000000000120  x19 00000000000000ac
2019-06-25 18:15:31.954 12797-12797/? A/DEBUG:     x20 000000000000313e  x21 00000000000000b2  x22 000000000000313e  x23 00000000ffffffff
2019-06-25 18:15:31.954 12797-12797/? A/DEBUG:     x24 ffffffffffffffff  x25 000000740a185020  x26 0000007409fd00b0  x27 0000000000000004
2019-06-25 18:15:31.954 12797-12797/? A/DEBUG:     x28 00000073851e7000  x29 0000007ffcecefc0
2019-06-25 18:15:31.954 12797-12797/? A/DEBUG:     sp  0000007ffceceef0  lr  0000007405ecb44c  pc  0000007405ecb46c
2019-06-25 18:15:31.955 12797-12797/? A/DEBUG: backtrace:
2019-06-25 18:15:31.955 12797-12797/? A/DEBUG:       #00 pc 000000000008246c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 7c07b297e5fadd3ee1f294701629152c)
2019-06-25 18:15:31.955 12797-12797/? A/DEBUG:       #01 pc 000000000008630c  /data/app/com.xinmang.camera.measure.altimeter-obOFjWE6TAFgautSQ_MAEQ==/lib/arm64/libfilament-jni.so (utils::TPanic<utils::PostconditionPanic>::panic(char const*, char const*, int, char const*, ...)+204) (BuildId: 033060fd6e78d97e5f2debbb2505dd0ea8800686)

**Comment by romainguy** [comment] 2019-06-25 21:03
Thank you for the report. Do you have more in the logs by any chance? It doesn't show where the panic occurred. Which version of Filament are you using? We had an issue on Q caused by the use of a private API but we fixed it a few weeks ago.

@pixelflinger Looks like we may have a crash on Q.

**Comment by Markcz** [comment] 2019-06-26 02:00
@pixelflinger 

dependencies {
       implementation "com.google.ar.sceneform:core:1.9.0"
       implementation "com.google.ar.sceneform.ux:sceneform-ux:1.9.0"implementation 
}

![屏幕快照 2019-06-26 09 49 31](https://user-images.githubusercontent.com/16713862/60145414-7c069300-97f8-11e9-98d1-48babacfd05e.png)

***External Library
![屏幕快照 2019-06-26 09 49 12](https://user-images.githubusercontent.com/16713862/60145400-70b36780-97f8-11e9-8160-9e0881392acf.png)

***Log
![屏幕快照 2019-06-26 09 56 54](https://user-images.githubusercontent.com/16713862/60145493-c7b93c80-97f8-11e9-9cb3-bbcee3d0b551.png)

**Comment by romainguy** [comment] 2019-06-26 02:04
Right that's a known issue with ARCore 1.9. It'll be fixed in the next version (the fix is already available in filament itself).

**Closed by romainguy** 2019-06-26 02:04 UTC
Labels: android, bug
