### ISSUE TITLE
Errors when building for VS 2017

### ISSUE THREAD

**Issue by Tenebralus** [google/filament#639] opened 2018-12-14 18:14 UTC
Tools used:
CMake 3.13.2
Microsoft Visual Studio Community 2017 Version 15.9.4
LLVM 7.0.0 64-bit Pre-Built Binary
Python 3.7.0
Windows 10 SDK for Windows 10, version 1809 (servicing release 10.0.17763.132)
filament 1.1.0

I am configuring the build using CMake:
![image](https://user-images.githubusercontent.com/13809397/50018101-74a33900-ffce-11e8-990a-fe2211654e5c.png)
![image](https://user-images.githubusercontent.com/13809397/50018137-8e448080-ffce-11e8-9324-35271077ac02.png)

After this I generate.
Keeping the settings to default, I do not know if I should change anything.
When I build the solution I get the following errors (build output, Release x64):
https://pastebin.com/pWwqD6xA

Second build, after above build (no rebuild)
https://pastebin.com/9Ra2tHLK

How do I fix these errors? I want to be able to use the 64-bit release version of the Filament PBR Renderer in my own project. Im also using OpenGL at the moment.

**Comment by bejado** [comment] 2018-12-15 00:04
Hey @Tenebralus I haven't used the CMake GUI much before, but when I run it with the same settings in your screenshot I see:

```
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
```

which is the **incorrect** compiler. I imagine this is because the correct environment variables are not set. Can you try invoking CMake manually in a x64 Native Tools Command Prompt for VS 2017?

```
cmake -T"LLVM" -G "Visual Studio 15 2017 Win64" ..
```

This sets the necessary env vars. Using that method I'm able to compile with VS2017 and Clang 7.

**Comment by Tenebralus** [comment] 2018-12-15 02:08
Ok, so I tried invoking using: 
`E:\cmake-3.13.2-win64-x64\bin\cmake -T"LLVM" -G "Visual Studio 15 2017 Win64" -S E:\Filament-cmake\filament -B E:\Filament-cmake\filament-done`
Output in Command Prompt:
![image](https://user-images.githubusercontent.com/13809397/50037818-ae4b6280-0015-11e9-96cc-1c6e83681375.png)

But I still get errors when building, the same errors from what I see:
https://pastebin.com/asP212KM
Second build:
https://pastebin.com/eg5k8qbF

**Comment by Tenebralus** [comment] 2018-12-15 02:54
By the way, which one is the correct compiler? The LLVM 7.0.0 one? So a path similar to C:\Program Files\LLVM\bin\clang-cl.exe? If so, how do I force that compiler?
I tried the -D CMAKE_C_COMPILER=C:\Program Files\LLVM\bin\clang-cl.exe option, which should update the cmake cache entry accordingly, but it does not work, it still checks for the compiler in the visual studio folder

**Comment by bejado** [comment] 2018-12-15 03:14
Yes, LLVM 7.0.0 is correct. Not sure why CMake lists Microsoft's compiler on the "Check for working CXX compiler" line. Judging by the build output it's still correctly using Clang at C:\Program Files\LLVM\bin\clang-cl.exe.

I was able to reproduce your bug, but only if I use Visual Studio GUI. If I invoke the build using the `msbuild` command, it succeeds. So it appears `msbuild` is doing things differently than Visual Studio. Try running this from CMake's out folder and seeing if it succeeds:

```
msbuild TNT.sln /m /p:configuration=Release
```

**Comment by Tenebralus** [comment] 2018-12-15 03:44
Still the same bug:
![image](https://user-images.githubusercontent.com/13809397/50038690-d5a92c00-0023-11e9-9eb4-00079b350054.png)

It is quite late for me at the moment, I will continue tomorrow (in about 10 hours). Thanks for the help so far.

**Comment by bejado** [comment] 2018-12-15 06:42
Can you check that you've pulled the latest master? I think the `undefined symbol: SHADERS_PACKAGE` was fixed in #637

**Comment by Tenebralus** [comment] 2018-12-15 15:18
It works! I was able to run samples\Release\lightbulb.exe samples\assets\models\monkey\monkey.obj successfully. Seems I downloaded an outdated version of filament earlier.

So, what libraries should I add to my project to be able to render with filament?

**Comment by thirdmenson** [comment] 2018-12-15 19:43
I was also able to build successfully using clang 7 and visual studio 2017.  I used this command

cmake -T"LLVM" -G "Visual Studio 15 2017 Win64"  -DCMAKE_CXX_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_C_COMPILER:PATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER:PATH="C:\Program Files\LLVM\bin\lld-link.exe" ../..

My mistake was to use -T "LLVM-vs2017" platform toolset and not specifying the explicit compiler and linker paths when using with clang 7 and visual studio 2017.  I suggest you guys add the above command for clang 7 and visual studio 2017 in the readme file so other users don't struggle to build using visual studio 2017 like I had to.

**Comment by romainguy** [comment] 2018-12-15 19:46
Thanks for the info @thirdmenson! We'll update the README.

@Tenebralus You'll need `bluegl.lib`, `filament.lib`, `filabridge.lib`, `filaflat.lib`, `smol-v.lib` and `utils.lib`. Basically everythng except `filameshio.lib` and `filament-jni.lib`.

**Comment by bejado** [comment] 2018-12-17 19:43
@Tenebralus You can find an example `Makefile` and instructions for linking against Filament [here](https://github.com/google/filament/tree/master/filament#windows).

**Comment by Tenebralus** [comment] 2018-12-17 20:45
Ok, just done that, but how does this benefit me? I am new to this makefile approach :)

**Comment by romainguy** [comment] 2018-12-17 20:47
It shows you what libraries you are required to link against.

**Comment by Tenebralus** [comment] 2018-12-17 20:49
aah, are you talking about the files under "2 warnings generated"?
![image](https://user-images.githubusercontent.com/13809397/50114750-a245e780-0245-11e9-9865-dcfcb2e08a9a.png)

**Comment by bejado** [comment] 2018-12-17 22:03
Correct, the `.lib` files are the static libraries required for using Filament.

**Closed by bejado** 2018-12-17 22:03 UTC
Labels: windows
