### ISSUE TITLE
Lack symbol files in release assets

### ISSUE THREAD

**Issue by nevermore1993** [google/filament#4912] opened 2021-12-01 02:18 UTC
**Describe the bug**
Hi, I was trying to debugging crashes, but there is no symbol files to decode the trace. Could you please provide symbol files in released assets, it would be really convenient and helpful for debug purpose.
Thanks

OS and backend
Android

**Comment by romainguy** [comment] 2021-12-01 02:21
Duplicate of #4884

**Closed** 2021-12-01 02:23 UTC
