### ISSUE TITLE
After enable temporal antiAliasing,scene show trailing shadow

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#4438] opened 2021-08-03 08:04 UTC
I want resolve specular aliasing issue,so I turn on all antialasing options used below code:

        view.antiAliasing = view.antiAliasing.apply {  View.AntiAliasing.FXAA}

        view.ambientOcclusionOptions = view .ambientOcclusionOptions.apply {
            upsampling = View.QualityLevel.HIGH
            quality = View.QualityLevel.HIGH
        }
        view.sampleCount = 4
        view.temporalAntiAliasingOptions = view.temporalAntiAliasingOptions.apply {
            enabled = true
        }

After enbalb temporalAntiAliasingOptions ,the specular aliasing  be resolved.But the scene show abnormal.
There are many ghost shadow after the model do any move.
Like below picture.

![screenshot](https://user-images.githubusercontent.com/3060688/127979279-3f837b99-a452-438c-8531-b91ae10a49f2.JPG)

Used in android phone and the 1.11.1 release.

**Comment by fanbinnet** [comment] 2021-08-03 08:27
Issue occour in Huawei MatePad Pro.
Test in some qualcomm platform ,there is no this issue.

**Comment by pixelflinger** [comment] 2021-08-03 20:57
This seems to be another gpu specific issue. We don't have a phone that reproduces the issue unfortunately.

**Comment by romainguy** [comment] 2021-08-04 00:50
An incorrect reprojection would cause the same issue on other platforms (but our TAA does show some ghosting in some situations, especially since we don't use per pixel motion vectors).

**Comment by fanbinnet** [comment] 2021-08-04 00:59
Is it possible that the GL_COLOR_BUFFER_BIT ？
I had a similar problem with different phenomenon between Huawei HISI and Qualcom for GL_COLOR_BUFFER_BIT.

**Comment by pixelflinger** [comment] 2021-08-04 01:41
Can you give not details about the issues you had with glClear ?

**Comment by fanbinnet** [comment] 2021-08-04 02:21
I use an framebuffer to draw,but the result have some nosie color.
Fixed by add " glClear(GL_COLOR_BUFFER_BIT); " before draw to framebuffer.

I just try below code, and there is no any change.
        modelViewer.renderer.clearOptions = modelViewer.renderer.clearOptions.apply {
            clear = true
            discard = false
        }

**Comment by romainguy** [comment] 2021-08-04 02:28
It shouldn't matter in this case anyway since we redraw the entire scree .

**Comment by pixelflinger** [comment] 2021-08-04 04:00
Could you try with a debug version of filament? In debug we are clearing buffers with debug colors, this might help narrow the problem down.

**Comment by fanbinnet** [comment] 2021-08-04 05:47
Now I use filament by gradle
    implementation 'com.google.android.filament:filament-android:1.11.1'
    implementation 'com.google.android.filament:gltfio-android:1.11.1'
    implementation 'com.google.android.filament:filament-utils-android:1.11.1'
Can you tell me how to use the debug version ? If I must build filament myself ?

**Comment by fanbinnet** [comment] 2021-08-04 06:08
If below image can indicate the cause is incorrect reprojection？

![1](https://user-images.githubusercontent.com/3060688/128130322-433ca158-eec4-4a0d-bbf6-42450cad9291.JPG)
![2](https://user-images.githubusercontent.com/3060688/128130328-16f2aa69-ff9b-4988-927d-2a0dafa57650.JPG)

**Comment by pixelflinger** [comment] 2021-08-04 07:29
No, an incorrect reprojection would only cause "ghosting" while moving, but the image would settle to something correct quickly.

I'm not sure what could cause these artifacts.

**Comment by fanbinnet** [comment] 2021-08-04 07:59
> No, an incorrect reprojection would only cause "ghosting" while moving, but the image would settle to something correct quickly.
> 
> I'm not sure what could cause these artifacts.

The image also will correct after few frames draw. The Image uploaded is  abnormal frame I capture.

**Comment by fanbinnet** [comment] 2021-08-04 10:03
Build the debug version filament, the  model show correct.But the skybox show abnormal.
![4](https://user-images.githubusercontent.com/3060688/128162293-83346517-94bf-4b19-890f-3fe2ca996558.JPG)

After remove the skybox from scene, the model show correct.
@pixelflinger 
So I  think “In debug we are clearing buffers with debug colors”，this maybe should resovle this issue.
Can you give me a patch ,or tell me how to change the code. I will try the change for this issue.

Thanks !

**Comment by fanbinnet** [comment] 2021-08-05 02:23
Comment line 2263 and line

**Comment by pixelflinger** [comment] 2021-08-05 16:44
Try to apply the patch below and see how it goes. It disables glInvalideFramebuffer and uses glClear instead.

[0001-don-t-use-glInvalidateFramebuffer.patch.zip](https://github.com/google/filament/files/6940283/0001-don-t-use-glInvalidateFramebuffer.patch.zip)

**Comment by fanbinnet** [comment] 2021-08-06 01:45
Use this path with debug version.
Model show nearly right but with some snow noise .
![snow_noise](https://user-images.githubusercontent.com/3060688/128443054-843f0efa-5f84-4a41-ac5c-f1520adcc961.JPG)

But the skybox show still abnormal like previously upload picture。

**Comment by pixelflinger** [comment] 2021-08-06 06:16
Unfortunately this looks like a driver bug, I'm not sure what we can do without a device to try to find a workaround.

**Comment by fanbinnet** [comment] 2021-08-06 07:45
I test with your patch,Your patch has also improved my work scene tremendously, with 80% noise cancellation,the skybox also show normal. My work scene used an old version filament for month ago.

**Comment by pixelflinger** [comment] 2021-08-11 23:39
I'm going to close this since it seems GPU specific and we don't have the h/w to test on.

**Closed by pixelflinger** 2021-08-11 23:39 UTC
Labels: bug, android, gpu specific
