### ISSUE TITLE
Web: Updating from Filament 1.22.2 to 1.25.3 appears to break shaders and/or geometry tangent frames

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#5864] opened 2022-08-01 22:28 UTC
**Bad normals/tangent frames in Web backend**
Trying to update from Filament 1.22.2 to 1.25.3.
Geometry normals/tangent frames used by shaders appear to be broken in the Web version.  The Windows version works fine.  To try to figure out what might be happening, I created a shader that outputs the world normal as the base color.  You can see the differences below.  Lighting is broken, as you would expect with bad normals.

I suspect the problem may have been introduced with recent updates to shader generation code.  I didn't notice any changes to the SurfaceOrientation::Builder code, which we use to generate tangent frames.

**Windows**
![image](https://user-images.githubusercontent.com/40642629/182254850-d9a43baa-6c6f-451e-9d1d-b82f5b8c19aa.png)

**Web**
![image](https://user-images.githubusercontent.com/40642629/182255164-71ed1197-1b57-4c9f-98a3-324ab16eb552.png)

**Shader used in screenshots**
Here is a copy of the shader used to generate the screenshots:

```
material {
    name : Lit_Simple,
    shadingModel : lit,
	doubleSided : false,
	colorWrite : true,
	depthWrite : true,
	depthCulling : true,
	culling : back,

    parameters : [
        {
            type : float3,
            name : baseColor
        },
        {
            type : float,
            name : metallic
        },
        {
            type : float,
            name : roughness
        },
        {
            type : float,
            name : reflectance
        }
    ],
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
	float3x3 tanFrame = getWorldTangentFrame();
	float3 straight = float3(0,0,1);
	float3 worldNormal = tanFrame * straight;
	material.baseColor = float4(worldNormal * 0.5 + 0.5, 1.0);
	material.normal = straight;
	material.reflectance = 0.0;
        material.metallic = materialParams.metallic;
        material.roughness = materialParams.roughness;
    }
}

```

**Additional context**
I am using **SurfaceOrientation::Builder** to generate the tangent frames.  My code did not change between Filament versions.

**Comment by romainguy** [comment] 2022-08-01 22:36
With which browser/OS does this happen? We're aware of rendering issues with DirectX via browsers on Windows.

**Comment by romainguy** [comment] 2022-08-01 22:36
See https://github.com/google/filament/issues/5859

**Comment by BStringhamVRSK** [comment] 2022-08-01 22:37
Using Chrome on Windows 10

**Comment by romainguy** [comment] 2022-08-01 22:40
Probably the same issue then :/

**Comment by BStringhamVRSK** [comment] 2022-08-01 22:41
If I roll back to 1.22.2, the web version works fine.  Is that consistent with what you're seeing with #5859 ?

**Comment by romainguy** [comment] 2022-08-01 22:44
Yes, the problem is somewhere between 1.25.0 and 1.25.3 (see the original discussion: https://github.com/google/filament/discussions/5824). Whatever change we made seems to hit a bug in ANGLE/DirectX. No other backend/platform is affected.

**Comment by BStringhamVRSK** [comment] 2022-08-01 22:56
I can confirm that changing Chrome's backend for ANGLE to OpenGL solves the issue (didn't even realize this was an option).  For others experiencing this, type `chrome://flags` into the Chrome address bar and then search for "Choose ANGLE graphics backend" on the page.

**Comment by prideout** [comment] 2022-08-15 17:18
Duplicate of #5859

**Closed by prideout** 2022-08-15 17:18 UTC
Labels: bug, web
