### ISSUE TITLE
【POD INSTALL】'type_traits' file not found, needs some help!

### ISSUE THREAD

**Issue by dandingol03** [google/filament#4894] opened 2021-11-26 05:48 UTC
**Describe the bug**
'type_traits' file not found

**To Reproduce**
1. create a `APP` xcode project
2. pod install filament
3. include `Engine.h` in any object-c file, such like 'ViewController.m'

**Expected behavior**
build successful

**Screenshots**
![image](https://user-images.githubusercontent.com/13013579/143533060-9d4b8348-71f2-4605-ba69-90cdd91b73c3.png)

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: [mac OS big sur 11.4]

**Smartphone (please complete the following information):**
 - Device: [iphone simulator]

**Comment by romainguy** [comment] 2021-11-26 06:00
Duplicate of #4893

**Closed by romainguy** 2021-11-26 06:00 UTC
