### ISSUE TITLE
Webgl Demos looks strange on web page.

### ISSUE THREAD

**Issue by briangavin** [google/filament#4469] opened 2021-08-08 07:05 UTC
Using the follow example.
https://google.github.io/filament/webgl/helmet.html

![image](https://user-images.githubusercontent.com/992784/128623836-68e434dc-e0a8-42cb-a8ef-a6b69200d6c1.png)

As the screenshot shows background looks strange.   Resizing the browser sometimes make the problem go away or reappear.   Sometimes also has a flicker problem.

I am using MS windows with a nvidia graphics card.

**Comment by romainguy** [comment] 2021-08-08 07:10
What version of Windows are you using, which graphics card do you have and which web browser/version is affected?

**Comment by briangavin** [comment] 2021-08-08 07:12
Windows 10, Nvidia 3060.  Chrome 92.0.4515.131

**Comment by cx20** [comment] 2021-08-08 10:30
Probably the same problem as #3151.

**Comment by pixelflinger** [comment] 2021-08-09 20:43
duplicate of #3151

**Closed by pixelflinger** 2021-08-09 20:43 UTC
Labels: duplicate
