### ISSUE TITLE
Crash when switching between GLB assets that have lights with shadow casting enabled

### ISSUE THREAD

**Issue by ast3rX** [google/filament#3774] opened 2021-04-07 08:02 UTC
**Describe the bug**
Switching between GLB assets crashes if the lights in the GLB are set to shadow casters in Metal. The assumption is that the bug was introduced in one of the commits around the time when the smart pointer ref counters were implemented. 

**To Reproduce**
1. Use gltf assets that include lights and enable shadow casting.
2. Try switching between these assets which would cause a consistent crash:
```
symbol stub for: std::__1::mutex::unlock()
filament::backend::metal::MetalExternalImage::isValid() const
filament::backend::metal::MetalExternalImage::getMetalTextureForDraw() const
filament::backend::metal::getOrCreateEmptyTexture(filament::backend::metal::MetalContext*)
symbol stub for: objc_retainAutoreleasedReturnValue
filament::backend::metal::StateCache<filament::backend::metal::SamplerState, id<MTLSamplerState> __strong, filament::backend::metal::SamplerStateCreator>::getOrCreateState(filament::backend::metal::SamplerState const&)
symbol stub for: objc_retainAutoreleasedReturnValue
```

**Expected behavior**
Stable behavior as in earlier filament builds after the initial fix of #3383. 

**Desktop (please complete the following information):**
 - Backend: Metal

**Comment by prideout** [comment] 2021-04-07 15:20
Thanks for the bug report!  @bejado you might be interested in this one.

**Comment by bejado** [comment] 2021-05-04 22:48
I'm unable to reproduce this on the latest build. @ast3rX, if you're still able to repro, could you please provide two GLB assets that cause the issue?

**Comment by ast3rX** [comment] 2021-05-07 12:44
@bejado , thank you for looking into this! It looks like it's a combination of having shadow casters and changing the indirect light with the glb files. If both conditons are true then there is a consistent crash.

I was able to repro this using the `hello-gltf` sample.
1. Change `setupMesh()` so it can reload the same glb multiple times as described in https://github.com/google/filament/issues/3383.
2. Add your lights to the scene and set them as shadow casters in `setupMesh()`:
```
 scene->addEntities(app.asset->getLightEntities(), app.asset->getLightEntityCount());
 auto& lm = engine->getLightManager();
 const auto begin = app.asset->getLightEntities();
 const auto end = begin + app.asset->getLightEntityCount();
 for(auto entity = begin; entity != end; ++entity) {
     auto instance = lm.getInstance(*entity);
     lm.setShadowCaster(instance, true);
 }
```
3. Update `setupIBL()` so it can reset the IBL:
```
void App::setupIbl() {
    if(app.iblTexture) {
        engine->destroy(app.iblTexture);
    }
    image::KtxBundle* iblBundle = new image::KtxBundle(RESOURCES_VENETIAN_CROSSROADS_2K_IBL_DATA,
                                                       RESOURCES_VENETIAN_CROSSROADS_2K_IBL_SIZE);
    float3 harmonics[9];
    iblBundle->getSphericalHarmonics(harmonics);
    app.iblTexture = image::ktx::createTexture(engine, iblBundle, false);

    if(app.indirectLight) {
        engine->destroy(app.indirectLight);
    }
    app.indirectLight = IndirectLight::Builder()
        .reflections(app.iblTexture)
        .irradiance(3, harmonics)
        .intensity(30000)
        .build(*engine);
    scene->setIndirectLight(app.indirectLight);
}
```
4. Call these setup methods every 10th time when the `pan()` gets called like this:
```
setupMesh();
setupIbl();
```

**Comment by ast3rX** [comment] 2021-05-20 12:01
@bejado, have you been able to repro the crash using the steps provided above?

**Comment by bejado** [comment] 2021-05-20 17:47
Hey @ast3rX, sorry haven't had a chance to try yet but I'll give it a go today.

**Comment by bejado** [comment] 2021-05-20 21:55
Sorry, I'm still unable to reproduce. I'm using a GLB with two spot lights. If you could upload a complete example with a GLB file that reproduces the crash, I'd be happy to take another look.

**Comment by ast3rX** [comment] 2021-05-23 06:48
I have uploaded the project with two glbs, both of these are crashing consistently during pan interaction with the provided repro on iOS Metal (device and simulator).
[hello-gltf.zip](https://github.com/google/filament/files/6527647/hello-gltf.zip)

**Comment by ast3rX** [comment] 2021-05-25 20:35
I pulled the latest main branch but I'm still seeing the same crash. I've saved the entire dump which also contains a `no texture bound at binding point` warning which is suspicious.
[crashdump.txt](https://github.com/google/filament/files/6542205/crashdump.txt)

**Comment by bejado** [comment] 2021-05-26 17:57
Are you actually seeing the "no texture bound at binding point" warning logged somewhere? What you uploaded is just the disassembly. A stack trace would be helpful as well.

**Comment by ast3rX** [comment] 2021-05-28 08:42
I'm not seeing the "no texture bound at binding point" warning in the log. I recompiled filament in debug mode and attached the relevant part of the iOS simulator log.
[log.txt](https://github.com/google/filament/files/6559493/log.txt)

**Comment by ast3rX** [comment] 2021-05-31 15:30
Based on my investigation this particular crash was introduced in the following commit: https://github.com/google/filament/commit/1189c9e29455dd170d2d86607ccf909791743ffb
@pixelflinger , do you have any idea?

**Comment by bejado** [comment] 2021-06-08 06:22
I'm glad you found a workaround... it's very bizarre that it crashes consistently for you, yet I'm not able to reproduce at all. I'm on a later Xcode (12.5); I'd be curious if upgrading Xcode fixes the issue, though that would be just as strange.

**Comment by ast3rX** [comment] 2021-06-09 19:08
Thanks, I will report back on the findings once I have the same Xcode version.

**Comment by bejado** [comment] 2021-07-08 18:21
Closing, but feel free to reopen if you're still able to reproduce with the latest Filament.

**Closed by bejado** 2021-07-08 18:21 UTC
Labels: bug, metal
