### ISSUE TITLE
glTF viewer not showing metal/rough textures

### ISSUE THREAD

**Issue by donmccurdy** [google/filament#503] opened 2018-11-20 04:24 UTC
**Describe the bug**

When testing a couple metal/rough models in glTF (`.glb`) format with the `gltf_viewer` sample, it appears that the metal/rough materials are not being applied.

**To Reproduce**
1. I tried viewing the following models with `gltf_viewer`. Both are collections of spheres with varying metal/roughness values.
2. `samples/gltf_viewer --ibl samples/envs/desert/ test_spheres.glb`

[Archive.zip](https://github.com/google/filament/files/2598059/Archive.zip)

**Expected behavior**

Result should look something like this:

![screen shot 2018-11-19 at 8 21 07 pm](https://user-images.githubusercontent.com/1848368/48751330-ab3c9c80-ec38-11e8-8c97-f514f593e3ae.png)

**Screenshots**

Actual results do not show metal/rough values:

| test_spheres | MetalRoughSpheres |
|---|---|
| ![screen shot 2018-11-19 at 8 22 20 pm](https://user-images.githubusercontent.com/1848368/48751370-d8894a80-ec38-11e8-995f-3783048f7669.png) | ![screen shot 2018-11-19 at 8 22 07 pm](https://user-images.githubusercontent.com/1848368/48751371-daeba480-ec38-11e8-90d4-3796341f0da7.png) |

**Desktop (please complete the following information):**
 - OS: macOS
 - GPU: NVIDIA GeForce GT 650M 1024 MB, Intel HD Graphics 4000 1536 MB
 - Backend: ?

**Additional context**

**Comment by prideout** [comment] 2018-11-20 07:29
See [PR 501](https://github.com/google/filament/pull/501) for details but we also saw a regression with OpenGL (lightbulb + sponza)

**Comment by romainguy** [comment] 2018-11-20 17:59
Actually this doesn't seem to be due to #501. Even when rolling back your rollback they don't show properly. It's probably an issue with Assimp or how we interpret Assimp's data.

@magicwhale

**Comment by romainguy** [comment] 2018-11-20 17:59
I get the following errors in the console:

```
The texture /Users/romainguy/Downloads/Archive/*0 does not exist
The texture /Users/romainguy/Downloads/Archive/*1 does not exist
The texture /Users/romainguy/Downloads/Archive/*0 does not exist
The texture /Users/romainguy/Downloads/Archive/*1 does not exist
The texture /Users/romainguy/Downloads/Archive/*0 does not exist
The texture /Users/romainguy/Downloads/Archive/*1 does not exist
The texture /Users/romainguy/Downloads/Archive/*0 does not exist
The texture /Users/romainguy/Downloads/Archive/*1 does not exist
The texture /Users/romainguy/Downloads/Archive/*0 does not exist
The texture /Users/romainguy/Downloads/Archive/*1 does not exist
```

Looks like we're trying to load external textures instead of embedded textures?

**Comment by romainguy** [comment] 2018-11-20 18:03
Fixed! Uninitialized variable issue :)

<img width="1136" alt="screen shot 2018-11-20 at 10 03 00 am" src="https://user-images.githubusercontent.com/869684/48793332-7b7aac80-ecab-11e8-868c-079f9993f977.png">

**Comment by donmccurdy** [comment] 2018-11-20 19:36
Thank you! I'll test this out soon.

**Comment by romainguy** [comment] 2018-11-20 20:06
The PR hasn't been merged yet btw.

-- 
Romain Guy
www.curious-creature.com

**Comment by romainguy** [comment] 2018-11-26 21:16
This issue is fixed in #505. We still have problems with some glTF assets:
- Vertex colors are not supported yet
- The way we compute tangents/bitangents is incorrect (the test asset doesn't render properly)

Assets like ScifiHelmet, DamagedHelmet, Sponza, etc. seem to render just fine though.

**Closed by romainguy** 2018-11-26 21:16 UTC
Labels: tools

**Comment by donmccurdy** [comment] 2018-11-29 06:40
This is excellent, thank you! Looking forward to using this viewer for testing. :)

![screen shot 2018-11-28 at 10 37 06 pm](https://user-images.githubusercontent.com/1848368/49203793-6ca49180-f35e-11e8-80b9-5103d19d5f40.png)

**Comment by romainguy** [comment] 2018-11-29 06:50
We have a few issues left to fix though. Vertex colors aren't handled, some textures don't load, etc. Nothing major but expect small problems ^^

**Comment by donmccurdy** [comment] 2018-11-29 06:59
A couple models I tested did crash: https://drive.google.com/open?id=1InFRtgLGdTC2apRAiWFN86ubsdVa8WbL. It's possible that's an error in the models — they did have some warnings in the validator. Are examples helpful, or better to wait until the known issues are solved?

**Comment by romainguy** [comment] 2018-11-29 07:05
Feel free to add any issue here: https://github.com/google/filament/issues/528

I haven't encountered crashes so far, so that's a new problem.
