### ISSUE TITLE
【Android】crash on joint transform in gltf model

### ISSUE THREAD

**Issue by xujikai** [google/filament#5915] opened 2022-08-15 07:18 UTC
**Describe the bug**
I have two UI MainActivity and GltfActivity，Normal operation for the first time，After entering the GltfActivity, exit and enter again，When joint transform is performed again，it will crash

**Code snippet**
```
private var mBodyNameArr = arrayOf(
      "LeftShoulder", "LeftArm", "LeftForeArm", "LeftHand",
      "RightShoulder", "RightArm", "RightForeArm", "RightHand"
)

mBodyNameArr.forEachIndexed { index, s ->
      val entity = modelViewer.asset?.getFirstEntityByName(s) ?: return@forEachIndexed
      val mBodySimpleFloatArr = FloatArray(16)
      modelViewer.engine.transformManager.getTransform(entity - 1, mBodySimpleFloatArr)

      // mBodySimpleFloatArr value change
      // ...

      modelViewer.engine.transformManager.setTransform(entity - 1, mBodySimpleFloatArr)
}
```

**Logs**
```
Build fingerprint: 'alps/gemini/gemini:10/QKQ1.210910.001/1652892654:userdebug/dev-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-08-15 14:54:11+0800
pid: 15690, tid: 15690, name: .app.testmotion  >>> com.app.testmotion <<<
uid: 10069
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x76bd40c6d4
    x0  000000741e639248  x1  000000741e639248  x2  00000000bd39460d  x3  00000073c85b9140
    x4  00000073c85b91c0  x5  00000073c85bab84  x6  00000073c85bab98  x7  0000000000000000
    x8  00000073c85baea0  x9  0000002f4e518340  x10 00000073c85b7f80  x11 00000073c85b5d40
    x12 00000008deaf489c  x13 000000000000000c  x14 00000073c85ba830  x15 00000073c85ba1c0
    x16 000000742ef48560  x17 00000074b2267380  x18 00000074b5126000  x19 000000741e639248
    x20 000000741e639248  x21 0000000000000000  x22 000000000000000c  x23 00000000bd39460d
    x24 00000002f4e51834  x25 0000000000000015  x26 0000000000000015  x27 0000000012d95b88
    x28 0000007ff90b8410  x29 0000007ff90b8410
    sp  0000007ff90b8370  lr  000000741f61ea6c  pc  000000741f62c598

backtrace:
      #00 pc 00000000000d5598  /data/app/com.app.testmotion-X13JlD8HGxZjDgIAIHW5cA==/lib/arm64/libfilament-jni.so (BuildId: d57ca2a2e3222f24e567669d4cba158e96bf9e1a)

stack:
         0000007ff90b82f0  00000074005c0000  [anon:libwebview reservation]
         0000007ff90b82f8  6101000000000000
         0000007ff90b8300  00000074b4bf5c00  [anon:libc_malloc]
         0000007ff90b8308  00000074b4c637c0  [anon:libc_malloc]
         0000007ff90b8310  00000074b4c3c380  [anon:libc_malloc]
         0000007ff90b8318  00000074b4bf5c00  [anon:libc_malloc]
         0000007ff90b8320  0000005c00000043
         0000007ff90b8328  00000074b4c63700  [anon:libc_malloc]
         0000007ff90b8330  0000007400430000  [anon:libwebview reservation]
         0000007ff90b8338  0000007ff90b8408  [stack]
         0000007ff90b8340  0000000000000000
         0000007ff90b8348  6197c67374536ca9
         0000007ff90b8350  0000007ff90b8410  [stack]
         0000007ff90b8358  0000000012d95b88  [anon:dalvik-main space (region space)]
         0000007ff90b8360  000000741f62bc30  /data/app/com.app.testmotion-X13JlD8HGxZjDgIAIHW5cA==/lib/arm64/libfilament-jni.so
         0000007ff90b8368  0000000000000015
    #00  0000007ff90b8370  000000741f61ea6c  /data/app/com.app.testmotion-X13JlD8HGxZjDgIAIHW5cA==/lib/arm64/libfilament-jni.so
         0000007ff90b8378  00000074b4c637c0  [anon:libc_malloc]
         0000007ff90b8380  000000741e639248  [anon:libc_malloc]
         0000007ff90b8388  0000007423976680  [anon:libc_malloc]
         0000007ff90b8390  000000741e639248  [anon:libc_malloc]
         0000007ff90b8398  00000074b4c637c0  [anon:libc_malloc]
         0000007ff90b83a0  00000000000000d2
         0000007ff90b83a8  0000007ff90b8408  [stack]
         0000007ff90b83b0  000000742eabf354  /apex/com.android.runtime/lib64/libart.so
         0000007ff90b83b8  0000000012dcc798  [anon:dalvik-main space (region space)]
         0000007ff90b83c0  00000000000000d2
         0000007ff90b83c8  0000000012de24f0  [anon:dalvik-main space (region space)]
         0000007ff90b83d0  0000000000000000
         0000007ff90b83d8  00000074b4bf5c00  [anon:libc_malloc]
         0000007ff90b83e0  6197c67374536ca9
         0000007ff90b83e8  0000000774536ca9
```

**Comment by prideout** [comment] 2022-08-15 17:23
Thanks for the bug report, this looks interesting.  Are you using our `ModelViewer` helper class?

**Comment by xujikai** [comment] 2022-08-16 06:55
Yes, I refer to the usage in sample-gltf-viewer，Version 1.25.4 is used

**Comment by xujikai** [comment] 2022-08-16 06:56
> Thanks for the bug report, this looks interesting. Are you using our `ModelViewer` helper class?

Yes, I refer to the usage in sample-gltf-viewer，Version 1.25.4 is used

**Comment by prideout** [comment] 2022-08-18 16:15
I would like to investigate but I'm having trouble reproducing.  Can you give more detailed steps?  Where does your code snippet go?

**Comment by xujikai** [comment] 2022-08-19 03:37
I created a simple project，https://github.com/xujikai/TestMotionSnip

**Comment by prideout** [comment] 2022-08-19 16:57
I was able to build and run your project, but I was not able get it to crash on an emulated Pixel 3a or a real Pixel 6 Pro.

I tried pushing the GLTF button, then the START button, then I go to the home screen and return to the app.  No crash.

**Comment by xujikai** [comment] 2022-08-21 02:47
@prideout My procedure is as follows: MainActivity -> GltfActivity -> click start button -> click stop button -> MainActivity -> GltfActivity -> click start button

**Comment by prideout** [comment] 2022-10-31 17:44
@pixelflinger I wasn't able to repro this particular issue back in August, but I have not yet followest the latest comment from @xujikai.  It is probably worth trying this out and closing if no repro can be achieved.

In general, the `ModelViewer` class could definitely use some love, @romainguy might be familiar with some of its deficiencies, e.g. as I recall, it cannot be instanced within a list-of-widgets.

**Comment by pixelflinger** [comment] 2022-11-03 22:14
@xujikai could you check if the problem still exists?

**Comment by xujikai** [comment] 2022-11-04 07:43
@pixelflinger I upgraded to 1.28.2，Follow these steps: MainActivity -> GltfActivity -> click start button -> click stop button(running result is normal) -> MainActivity -> GltfActivity -> click start button(running result is separation of model and texture) -> click stop -> MainActivity -> GltfActivity -> click start button(running result is crash or no animation)

**Comment by poweifeng** [comment] 2023-07-20 22:05
If your code, it looks like this: 

```
   private fun setBodyMorph() {
        val manager = modelViewer.engine.transformManager
        val asset = modelViewer.asset

        motionBean?.curves?.forEachIndexed { _, it ->
            if (mFrameIndex >= it.rotas.size) mFrameIndex = 0
            val rota = it.rotas[mFrameIndex]
            val x = rota.x
            val y = rota.y
            val z = rota.z
            val w = rota.w

            val m00 = 1 - 2 * pow(y, 2f) - 2 * pow(z, 2f);
            val m01 = 2 * x * y - 2 * w * z;
            val m02 = 2 * x * z + 2 * w * y;

            val m10 = 2 * x * y + 2 * w * z;
            val m11 = 1 - 2 * pow(x, 2f) - 2 * pow(z, 2f);
            val m12 = 2 * y * z - 2 * w * x;

            val m20 = 2 * x * z - 2 * w * y;
            val m21 = 2 * y * z + 2 * w * x;
            val m22 = 1 - 2 * pow(x, 2f) - 2 * pow(y, 2f);

            val entity = asset?.getFirstEntityByName(it.name) ?: return@forEachIndexed
            manager.getTransform(entity - 1, mBodySimpleFloatArr)
            mBodySimpleFloatArr[0] = m00
            mBodySimpleFloatArr[1] = -m10
            mBodySimpleFloatArr[2] = -m20
            mBodySimpleFloatArr[4] = -m01
            mBodySimpleFloatArr[5] = m11
            mBodySimpleFloatArr[6] = m21
            mBodySimpleFloatArr[8] = -m02
            mBodySimpleFloatArr[9] = m12
            mBodySimpleFloatArr[10] = m22

            manager.setTransform(entity - 1, mBodySimpleFloatArr)
        }

        mFrameIndex++
    }
```

The `manager.getTransform` and `manager.setTransform` call should be called on the instance and not the entity.  So you can change it to

```
    private fun setBodyMorph() {
        val manager = modelViewer.engine.transformManager
        val asset = modelViewer.asset

        motionBean?.curves?.forEachIndexed { _, it ->
            if (mFrameIndex >= it.rotas.size) mFrameIndex = 0
            val rota = it.rotas[mFrameIndex]
            val x = rota.x
            val y = rota.y
            val z = rota.z
            val w = rota.w

            val m00 = 1 - 2 * pow(y, 2f) - 2 * pow(z, 2f);
            val m01 = 2 * x * y - 2 * w * z;
            val m02 = 2 * x * z + 2 * w * y;

            val m10 = 2 * x * y + 2 * w * z;
            val m11 = 1 - 2 * pow(x, 2f) - 2 * pow(z, 2f);
            val m12 = 2 * y * z - 2 * w * x;

            val m20 = 2 * x * z - 2 * w * y;
            val m21 = 2 * y * z + 2 * w * x;
            val m22 = 1 - 2 * pow(x, 2f) - 2 * pow(y, 2f);

            val entity = asset?.getFirstEntityByName(it.name) ?: return@forEachIndexed
            val inst = manager.getInstance(entity);
            manager.getTransform(inst, mBodySimpleFloatArr)
            mBodySimpleFloatArr[0] = m00
            mBodySimpleFloatArr[1] = -m10
            mBodySimpleFloatArr[2] = -m20
            mBodySimpleFloatArr[4] = -m01
            mBodySimpleFloatArr[5] = m11
            mBodySimpleFloatArr[6] = m21
            mBodySimpleFloatArr[8] = -m02
            mBodySimpleFloatArr[9] = m12
            mBodySimpleFloatArr[10] = m22

            manager.setTransform(inst, mBodySimpleFloatArr)
        }

        mFrameIndex++
    }
```

**Closed by poweifeng** 2023-07-20 22:05 UTC
Labels: bug, android, gltf
