### ISSUE TITLE
Please support building shared libraries instead of static libraries

### ISSUE THREAD

**Issue by yurivict** [google/filament#5953] opened 2022-08-19 15:45 UTC
**Is your feature request related to a problem? Please describe.**
Shared libraries make tracking dependencies much easier in the context of maintaining a port.
I am working on the FreeBSD port for filament and it would be very desirable if filament would be able to build shared libraries. This was it would be clear what other libraries binaries depend on.

**Describe the solution you'd like**
Project should respect cmake's standard variable ```BUILD_SHARED_LIBS```.

**Comment by romainguy** [comment] 2022-08-19 16:29
Duplicate of issue #1075

**Closed by romainguy** 2022-08-19 16:29 UTC
