### ISSUE TITLE
lightbulb app run with -m will no response on win10 , opengl backend

### ISSUE THREAD

**Issue by BillyUSA** [google/filament#2219] opened 2020-03-06 11:10 UTC
may be a long loop at this:
  
 template<typename F>
    void forEachSetBit(F exec) const noexcept {
        for (size_t i = 0; i < N; i++) {
            T v = storage[i];
            while (v) {
                T k = utils::ctz(v);
                v &= ~(T(1) << k);
                exec(size_t(k + BITS_PER_WORD * i));
            }
        }
    }
 
 storage value : {4294967297, 4294967296, 0, 0}

**Comment by romainguy** [comment] 2020-03-06 16:30
This loop iterates over bit set, it shouldn't take long even with those values.

**Comment by bejado** [comment] 2020-03-07 01:34
I'm able to reproduce this, it looks like `forEachSetBit` is getting into an infinite loop somehow.

**Comment by bejado** [comment] 2020-03-10 00:07
`details::ctz(0x100000000)` returns `63`, when it should return `32`.

**Comment by romainguy** [comment] 2020-03-10 01:12
That would explain :)

**Comment by romainguy** [comment] 2020-03-10 20:32
This should be fixed by #2227

**Closed** 2020-03-10 22:42 UTC
