### ISSUE TITLE
how to use multi-pass  with filament?

### ISSUE THREAD

**Issue by feiziang** [google/filament#3129] opened 2020-09-27 02:37 UTC
**Is your feature request related to a problem? Please describe.**
How to use multi-pass  with filament?
Many scenarios require more than one Pass to render

**Describe the solution you'd like**
maybe like Unity? we can relize multi-pass with GLSL

**Comment by romainguy** [comment] 2020-09-27 02:48
Can you describe your request in more detail? You can render to textures and/or use multiple views stacked on top of each other. If you are talking about multi pass materials this is not supported and I'm not sure that's something we want to do.

**Comment by feiziang** [comment] 2020-09-27 02:57
![image](https://user-images.githubusercontent.com/46670194/94354655-f7b45700-00af-11eb-8b9b-55ea3ec61c85.png)
like this. I don't know if "render to textures and/or use multiple views stacked on top of each other" can work?

**Comment by romainguy** [comment] 2020-09-27 02:59
Well it depends on the effect you are trying to implement.

**Comment by feiziang** [comment] 2020-09-27 03:00
For example :  cartoon style rendering needs 2 pass.   What should I do with filament?

**Comment by romainguy** [comment] 2020-09-28 15:50
One way to do it is to have 2 `Renderable`s with two different materials. The renderables can share a parent transform and the mesh data. It's slightly more expensive than true multi-pass support but not overly so.

**Comment by romainguy** [comment] 2020-09-28 15:51
Duplicate of [issue #1690](https://github.com/google/filament/issues/1690).

**Closed** 2020-09-28 15:51 UTC
Labels: duplicate

**Comment by feiziang** [comment] 2020-09-29 00:15
Thank you so much!



发自我的iPhone


------------------ Original ------------------

**Comment by RippleZou** [comment] 2021-06-28 08:52
> One way to do it is to have 2 `Renderable`s with two different materials. The renderables can share a parent transform and the mesh data. It's slightly more expensive than true multi-pass support but not overly so.

Can I use multi-pass on only one material?

**Comment by cjsliuj** [comment] 2021-07-06 07:52
No you can not. 
One material multi-pass just Syntactic sugar.

**Comment by dandingol03** [comment] 2022-04-23 16:22
> Thank you so much! 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Romain Guy <notifications@github.com&gt; Date: Mon,Sep 28,2020 11:50 PM To: google/filament <filament@noreply.github.com&gt; Cc: feiziang <2282714918@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [google/filament] how to use multi-pass with filament? (#3129) One way to do it is to have 2 Renderables with two different materials. The renderables can share a parent transform and the mesh data. It's slightly more expensive than true multi-pass support but not overly so. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hi, recently i also need to migrate unity fur shader to filament. Have you solve this problem? Is there any possible you can share me with the code or demo? Thanks in advance.
大佬我最近也在迁unity的shader，也是苦于multi pass不支持，如果你实现了能给我看看比如demo级别的代码嘛～
