### ISSUE TITLE
Build.sh no longer compiles due to Allocator.h

### ISSUE THREAD

**Issue by uromastix87** [google/filament#390] opened 2018-10-17 03:10 UTC
**Describe the bug**
Attempted to compile using build.sh and get an error after ninja has begun building.

**To Reproduce**
pull repo
export CC and CXX as /usr/bin/clang and /usr/bin/clang++
run build.sh

**Screenshots**
Here is the output.
```
[rfebbo@dextella filament]$ export CXX=/usr/bin/clang++ 
[rfebbo@dextella filament]$ export CC=/usr/bin/clang
[rfebbo@dextella filament]$ ./build.sh debug
which: no javac in (/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Warning: JAVA_HOME is not set, skipping Java projects
Building debug in out/cmake-debug...
-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang
CMake Warning (dev) at third_party/spirv-tools/CMakeLists.txt:76 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'SKIP_SPIRV_TOOLS_INSTALL'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "3.7") 
CMake Warning (dev) at third_party/spirv-tools/CMakeLists.txt:210 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'SPIRV_SKIP_EXECUTABLES'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at third_party/spirv-tools/CMakeLists.txt:213 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'SPIRV_SKIP_TESTS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/rfebbo/Documents/git/filament/out/cmake-debug
[21/950] Building CXX object third_par...eFiles/gtest.dir/__/src/gtest-all.cc.o
FAILED: libs/utils/CMakeFiles/test_utils.dir/test/test_Allocators.cpp.o 
/usr/bin/clang++  -DFILAMENT_DRIVER_SUPPORTS_VULKAN -I../../libs/utils/include -I../../third_party/libgtest/tnt/../include -I../../third_party/robin-map/tnt/.. -I../../libs/math/include -std=c++14 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fcolor-diagnostics -DTNT_DEV -g    -pthread -MD -MT libs/utils/CMakeFiles/test_utils.dir/test/test_Allocators.cpp.o -MF libs/utils/CMakeFiles/test_utils.dir/test/test_Allocators.cpp.o.d -o libs/utils/CMakeFiles/test_utils.dir/test/test_Allocators.cpp.o -c ../../libs/utils/test/test_Allocators.cpp
In file included from ../../libs/utils/test/test_Allocators.cpp:24:
../../libs/utils/include/utils/Allocator.h:639:32: error: no matching member function for call to 'alloc'
        return mArena.template alloc(size, alignment, 0);
               ~~~~~~~~~~~~~~~~^~~~~
../../libs/utils/test/test_Allocators.cpp:258:17: note: in instantiation of member function 'utils::ArenaScope<utils::Arena<utils::LinearAllocator, utils::LockingPolicy::NoLock, utils::TrackingPolicy::Untracked> >::allocate' requested here
        p = ssa.allocate(1024);
                ^
../../libs/utils/include/utils/Allocator.h:487:8: note: candidate template ignored: couldn't infer template argument 'T'
    T* alloc(size_t count, size_t alignment = alignof(T), size_t extra = 0) noexcept {
       ^
1 error generated.
[30/950] Building CXX object libs/math...les/test_math.dir/tests/test_mat.cpp.o
ninja: build stopped: subcommand failed.

```

**Desktop (please complete the following information):**
 - OS:  4.18.12-arch1-1-ARCH 

**Additional context**
The build was working fine around September 30th. Not sure what happened since. Maybe its to do with clang 7.0?

PS Thanks for helping me with my makefile issue! I'm using the binaries in the meantime, but I wanted to get at the .inc generated material files.

**Comment by romainguy** [comment] 2018-10-17 03:17
Thanks for the report, I'll take a look tomorrow. It should be an easy fix. We do compile our Android builds with clang 7 so I'm not sure what could have changed to explain this.

**Comment by pixelflinger** [comment] 2018-10-17 04:18
This is similar to #358

**Comment by romainguy** [comment] 2018-10-17 21:46
Yes, it's a dupe of #358. I'll close this one.

**Closed by romainguy** 2018-10-17 21:46 UTC
