### ISSUE TITLE
bug in jointed cloth animation

### ISSUE THREAD

**Issue by coldgemini** [google/filament#3707] opened 2021-03-26 12:30 UTC
**Describe the bug**
The animation results of the attached gltf file are quite different when shown in filament v.s. in babylon.js, with the former being a bit disruptive and the latter quite smooth.
[test(1).gltf.zip](https://github.com/google/filament/files/6211775/test.1.gltf.zip)

**Screenshots**
From Filament
![image](https://user-images.githubusercontent.com/33364009/112631489-e89d3e80-8e71-11eb-9444-3a390e939c46.png)
From Babylon.js
![image](https://user-images.githubusercontent.com/33364009/112631454-de7b4000-8e71-11eb-838d-ba4367e73c97.png)

**Filament Version**
1.9.10 in vscode plugin
![image](https://user-images.githubusercontent.com/33364009/112632725-76c5f480-8e73-11eb-96b4-89dfadaf2a24.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Backend: [OpenGL]
![image](https://user-images.githubusercontent.com/33364009/112632485-25b60080-8e73-11eb-9fa8-a8eb9b1e1bf3.png)

**Comment by prideout** [comment] 2021-03-29 15:37
@coldgemini I think the zip file is missing a bin file.

**Comment by coldgemini** [comment] 2021-03-30 03:06
I uploaded the glb file.
Thanks.

[test(1).glb.zip](https://github.com/google/filament/files/6225900/test.1.glb.zip)

**Comment by prideout** [comment] 2021-03-30 15:29
Thanks for the bug report, I am able to repro.  Maya exports skinning as two separate node hierarchies and we might have a bug in how we deal with this.

As an aside, Three and Babylon have "flashing" issues after the cloth has collapsed, perhaps due to degenerate polygons or depth fighting.  Also, you might want to set `doubleSided` to true.

**Comment by prideout** [comment] 2021-03-30 15:50
I checked and we correctly handle all the scenarios tested here, include separate node hierarchies:

https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Positive/Animation_Skin/README.md

This might be an issue with the fact that there are 32 nested joint nodes, in theory we support this but I don't think I've tested a model with this many joints.

**Comment by flyingonly** [comment] 2021-03-31 08:47
We think that the problem has nothing to do with the hierarchy. It's caused by the decomposition and composition of the matrix. In the makeBone function, the matrix is decomposed and then composed in the shader. It can be done with the pure transform matrix, however, the bone matrix is not only the transform matrix, but the product of the transform matrix and the inverse bind matrix. And the process may cause the matrix cannot be re-composed, especially when the transform matrix has a scale which differs in each axis, while the inverse bind matrix has a rotation along the axes.
A simple test can be done in filament_test. Add one rotation matrix after the matrix generated by the product. Then the test will not pass.
<img width="1750" alt="截屏2021-03-31 下午4 33 22" src="https://user-images.githubusercontent.com/9585829/113116740-506fd280-9240-11eb-9da7-9161f913b578.png">

**Comment by prideout** [comment] 2021-03-31 16:01
This is great, thank you so much for investigating!  I'm surprised that we haven't seen this issue in any other models yet.

**Comment by prideout** [comment] 2021-04-01 18:55
This is not a gltfio issue, it's a known limitation in Filament itself.  We store decomposed transforms for bones because they are more compact than two separate matrices (positions + normals).  We implemented this in 2018 via #383.

Therefore we do not support shearing.  In general glTF disallows shearing for nodes, although it does not explicitly place restrictions on the skinning matrix.

Shearing matrices can be decomposed into (rotation + non_uniform_scale + rotation).

In this particular case, the finalized bone matrix (which includes the inverse bind matrix, as you mentioned) has shear.

Note that support for non-uniform scale with skinning is a point of contention within the glTF community (see [here](https://github.com/KhronosGroup/glTF/issues/1665)).

I wonder if you could achieve your desired effect in a different way, e.g. via morphing rather than skinning?

**Comment by prideout** [comment] 2021-04-07 03:13
Filament does not support shear in the skinning matrix, closing.

**Closed by prideout** 2021-04-07 03:13 UTC
Labels: gltfio
