### ISSUE TITLE
Cannot assign anymore to material.clipSpaceTransform

### ISSUE THREAD

**Issue by kpeeters** [google/filament#3045] opened 2020-09-04 10:18 UTC
In everything up to and including 1.8.1 it was possible to have a vertex block like

    vertex {
        void materialVertex(inout MaterialVertexInputs material) {
            material.clipSpaceTransform = mat4(2.0);
        }
    }

In the current main branch, this makes `matc` bail out with

    ERROR: depth_main.vs:24: 'material' : undeclared identifier 
    ERROR: depth_main.vs:24: 'getClipSpaceTransform' : no matching overloaded function found 
    ERROR: depth_main.vs:24: '' : missing #endif 
    ERROR: depth_main.vs:24: 'assign' :  cannot convert from ' const float' to ' gl_Position highp 4-component vector of float Position'
    ERROR: depth_main.vs:24: '' : compilation terminated 
    ERROR: 5 compilation errors.  No code generated.

Seems to happen independent of platform or api.  

Has this api changed or is this a regression? Thanks!

**Comment by romainguy** [comment] 2020-09-04 15:25
It's a regression. The clip space transform wasn't applied to depth shaders, looks like the fix introduced its own issue. We'll fix it.

**Comment by romainguy** [comment] 2020-09-04 17:19
I just pushed a fix in https://github.com/google/filament/commit/3092063ebba2cb24a6dfc5ff97121fdfa09e1da1. Sorry for the trouble.

**Closed by romainguy** 2020-09-04 17:19 UTC
Labels: bug
