### ISSUE TITLE
Camera pan clips shadows?

### ISSUE THREAD

**Issue by kpeeters** [google/filament#3552] opened 2021-02-18 22:17 UTC
I am trying to implement a simple 2D panning of the viewport by pre-multiplying the camera matrix with a translation; something like

    auto cp = camera->getCullingProjectionMatrix();
 
    math::mat4f trans(math::float4{1.0f,      0,      0,     0},
                      math::float4{0,      1.0f,      0,     0},
                      math::float4{0,         0,   1.0f,     0},
                      math::float4{pan.x, pan.y,      0,  1.0f} );
 
    camera->setCustomProjection(trans * cp, camera_near, camera_far);

This pans the view fine, but it also clips shadows depending on how far I pan. Using `getProjectionMatrix` instead of `getCullingProjectionMatrix` does not change that.

Am I misunderstanding the logic or conventions followed in Filament for the camera matrix? I am doing something fairly similar in three.js, where it works as expected. Thanks!

(If there is a better way to pan the view then I'm all ears. Would like to avoid changing the viewport as it tends to be slower with three.js than changing the camera matrix, and would require me to change more backend code. In any case, I'd like to understand what I am doing wrong above).

**Comment by romainguy** [comment] 2021-02-18 22:22
@pixelflinger can confirm, but if you are not updating the model matrix of the camera various internal computations will be incorrect. In particular Filament performs tight clipping of the shadow maps which may rely on the camera position somewhere. Other computations for lighting would be affected too.

**Comment by pixelflinger** [comment] 2021-02-18 22:32
Yes, it's not documented properly, but the projection can't have a translation in it. To pan the camera, you can simply update its model matrix with your `pan` values.

**Comment by kpeeters** [comment] 2021-02-18 22:54
But if I change the camera's model matrix the camera moves within the scene, seeing objects from a different angle. What I am after is simply a translation of the final rendered image on the screen, as if I had translated the viewport. So purely a 2D thing in screen space.

**Comment by pixelflinger** [comment] 2021-02-19 00:08
Ah... I see. I'm going to have to investigate then. Can you attach a screenshot of what you're seeing?

**Comment by kpeeters** [comment] 2021-02-19 19:37
The problem looks *very* similar to what I reported ages ago in https://github.com/google/filament/issues/742 (which was my mistake, not Filament's, but I think this is different, so please read on). So my first response was to carefully check my bounding boxes once again. But I compute them with `filament::RenderableManager::computeAABB` now and I just don't see any error with them. Basically, I get that kind of effect, but with the camera located somewhere to the right, and the light shining towards the camera. 

So without pan it looks like the view-from-the-right of the bottom figure (light shining towards the camera, the object casting a shadow towards the camera), but once I start panning to the right, the shadow gets clipped more and more, to look like the top figure there (but again viewed from a camera located to the right). Eventually the shadow disappears altogether. 

Similar for moving up/down: if I pan the camera up, the shadow gets clipped from the bottom, and that clip moves further and further up as I pan more up. It is not just the shadow plane that is affected. Self-shadowing similarly clips. The clip is not a straight vertical line but seems to be influenced by perspective (that is to say, it's not just a 2D clip in screen space).

Was too busy today but I'll try to cook up a small example and some screenshots later if the above does not ring any bells. Let me know.

**Comment by pixelflinger** [comment] 2021-02-25 03:24
Is it just the shadows that get clipped, or the geometry as well? What about dynamic lighting?

**Comment by pixelflinger** [comment] 2021-03-05 23:51
I tried to reproduce this, but I didn't see any problem with the directional light's shadow. Did you see the problem with all types of shadows?

**Comment by kpeeters** [comment] 2021-03-06 09:30
Yes, all shadows. Sorry for the silence, very busy here, and I wanted to see if I could get it down to a minimal example. Thanks for the new 'shift' function, will use that for further tests. Will get back on this sometime next week.

**Comment by pixelflinger** [comment] 2021-03-07 01:22
I've been thinking more about it and I think I may have an idea of why you're having some issues. I'll look into it on Monday.

I think this might be because I have some coffee that makes assumption about what's on the projection matrix in a few places.

A minimal example would be great though.

**Comment by pixelflinger** [comment] 2021-03-07 08:19
@kpeeters would you be able to try this:

In `Camera.cpp` around line 205, replace the implementation of `inverseProjection(const math::details::TMat44<T>& p)` with `return inverse(p);`

```
template<typename T>
math::details::TMat44<T> inverseProjection(const math::details::TMat44<T>& p) noexcept {
    return inverse(p);
}
```

Does it solve the problem or make it better?

Thanks!

**Comment by kpeeters** [comment] 2021-03-08 10:07
That doesn't seem to make any difference, unfortunately. I'll send you a video later today.

**Comment by pixelflinger** [comment] 2021-03-09 03:06
I did more investigation today and as far as I can tell, by code inspection, it should work (famous last words).

**Comment by romainguy** [comment] 2021-03-09 22:18
It doesn't look like the shadow is getting clipped really, but more like we don't position the shadow properly.

**Comment by kpeeters** [comment] 2021-03-09 22:20
If you look very closely, you see that the angle of the shadow changes when it starts `clipping'. It is not just shifting to the right (sorry, this doesn't come out very clearly here).

**Comment by pixelflinger** [comment] 2021-03-14 07:31
Can you share the test  app (source) with us?

**Comment by pixelflinger** [comment] 2021-06-15 22:19
@kpeeters can you share the test app with us? I've not been able to reproduce this issue.

**Comment by kpeeters** [comment] 2021-06-15 23:09
That clip is from the actual app, which is far too messy to feed to you. I'll try to give this another shot soon when I find some time.

**Comment by kpeeters** [comment] 2021-07-14 20:04
This turned out to be caused by `MaterialInstance::setScissor`; dropping this makes the clipping effect go away. So I am probably not understanding the coordinate system used for that call. Are those NDCs? Do they change/do I need to compensate when using `Camera::setShift`? It's funny that this only clipped ground plane shadows, not the actual model, even though I used exactly the same `setScissor` call for the two materials.

**Comment by romainguy** [comment] 2021-07-14 20:05
The scissor is set in viewport coordinates.

**Closed** 2021-08-02 18:48 UTC
