### ISSUE TITLE
Error when run ./build.sh -p android release

### ISSUE THREAD

**Issue by at-duymai** [google/filament#3292] opened 2020-11-16 10:03 UTC
Hello. I am trying to try running android demos on my mac. (Catalina 10.15.4)
I followed the instructions in the BUILDING.md file and received the following error: 
[error.txt](https://github.com/google/filament/files/5545463/error.txt)
My versions: 
Android studio 4.1.1, NDK 22.0.6917172, Ninja 1.10.1
![Screen Shot 2020-11-16 at 4 59 51 PM](https://user-images.githubusercontent.com/25318291/99239090-25ef2100-282d-11eb-80bc-be712c96e9b0.png)
![Screen Shot 2020-11-16 at 5 01 07 PM](https://user-images.githubusercontent.com/25318291/99239216-546cfc00-282d-11eb-8489-17755f3e8387.png)

**Comment by prideout** [comment] 2020-11-16 16:46
Thanks for the bug report, I can reproduce this too.  It might be due to our SPIRV update.

**Comment by bejado** [comment] 2020-11-16 22:38
Fixed by #3296

**Closed by bejado** 2020-11-16 22:38 UTC
