### ISSUE TITLE
Vulkan Validation Layer Errors on all Demos

### ISSUE THREAD

**Issue by jwinarske** [google/filament#4795] opened 2021-11-01 23:06 UTC
**Describe the bug**
Running any of the Demo apps in debug generate SIGINT, preventing further debugging.  Demos should be validation layer free.

**To Reproduce**
1. On Linux machine using CLion open repo root
2. Configure settings to build debug with only Vulkan backed enabled
3. Start debugging a demo

**Expected behavior**
Not to experience validation layer errors.

**Logs**
One example:
```
VULKAN ERROR: (UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout) Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x7f64608d40c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buffer expects VkImage 0xab64de0000000020[] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.
Signal: SIGINT (Interrupt)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 / Fedora 34
 - GPU: Integrated AMD (Ubuntu) / AMD 6800XT (Fedora 34)
 - Backend: Vulkan

**Comment by romainguy** [comment] 2021-11-01 23:44
Duplicate of issue #4768

**Closed** 2021-11-01 23:44 UTC
Labels: bug, duplicate, vulkan
