### ISSUE TITLE
Engine destroyed swiping page ViewPager Android

### ISSUE THREAD

**Issue by Berna78** [google/filament#5543] opened 2022-05-12 14:24 UTC
**Describe the bug**
After swipe from two fragment (viewpager) application crash

**To Reproduce**
The crash occurs if in pagerview I have a fragment that contains a modelView and this is put twice in onpause.

**Logs**
When switching from onPause to OnResume for the first time I get the following error, but app doesn't crash:
E/SurfaceView: Exception configuring surface
    java.lang.IllegalStateException: Calling method on destroyed Engine
        at com.google.android.filament.Engine.getNativeObject(Engine.java:661)
        at com.google.android.filament.Engine.createSwapChain(Engine.java:296)
        at com.google.android.filament.Engine.createSwapChain(Engine.java:274)
        at com.google.android.filament.utils.ModelViewer$SurfaceCallback.onNativeWindowChanged(ModelViewer.kt:379)
        at com.google.android.filament.android.UiHelper.createSwapChain(UiHelper.java:570)
        at com.google.android.filament.android.UiHelper.access$100(UiHelper.java:120)
        at com.google.android.filament.android.UiHelper$1.surfaceCreated(UiHelper.java:405)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:1284)
        at android.view.SurfaceView$1.onPreDraw(SurfaceView.java:225)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1124)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3854)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:744)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Following a subsequent page swipe (onPause):
A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7a0000007a in tid 17542 (it.alghoandroid), pid 17542 (it.alghoandroid)

**Smartphone (please complete the following information):**
 - Device: Samsung A80
 - OS: Android 11

**Comment by romainguy** [comment] 2022-05-12 15:39
Which version of filament are you using and more importantly how are you using Filament?

**Comment by romainguy** [comment] 2022-05-12 16:38
Yes but how? How is Filament used and setup in your code?

**Comment by Berna78** [comment] 2022-05-12 16:48
I setup Filament using like reference android sample gltf-viewer.

**Comment by romainguy** [comment] 2022-05-12 17:38
So you are using ModelViewer?

**Comment by Berna78** [comment] 2022-05-12 18:03
Yes I use ModelViewer. I forgot to say that I use Java.

**Comment by romainguy** [comment] 2022-05-13 15:59
@Berna78 The solution for now is to use the constructor of `ModelViewer` that lets you pass your own `Engine` so you can control the lifetime.

**Comment by Berna78** [comment] 2022-05-13 16:43
I already use the costrutor with Engine parameter.   I tried both to store the instance and to create a new one every time you enter onresume. I also notice that if I don't recreate the ModelViewer every time you go back to the page, the surfaceview doesn't show the model. a new surfaceView linked to a new ModelViewer onResume and removing it each time OnPause.

**Comment by Berna78** [comment] 2022-05-13 16:47
I'm sorry I missed a piece of the message..
If it can help, I have taken care of it I create a new surfaceView linked to a new ModelViewer onResume and removing it each time OnPause.

**Comment by romainguy** [comment] 2022-05-13 16:48
Could you please show your code, it would be easier.

**Comment by Berna78** [comment] 2022-05-13 16:58
[https://we.tl/t-yw5P8qJYVe](url) this is my fragment.

**Comment by romainguy** [comment] 2022-05-13 17:07
@prideout We still destroy the `Engine` when `ModelViewer` is detached, even if the `Engine` was created by the caller, is that normal? I thought we fixed this recently? Recycling containers like `ViewPager` or `RecyclerView` will detach/attach views multiple times as you scroll through the list.

**Comment by romainguy** [comment] 2022-05-24 18:55
Duplicate of issue #4724

**Comment by romainguy** [comment] 2022-06-08 16:30
Closing because it's a duplicate

**Closed by romainguy** 2022-06-08 16:30 UTC
Labels: bug, duplicate, android, gltf
