### ISSUE TITLE
Black Screen in sample-hello-camera on Multiple Device

### ISSUE THREAD

**Issue by gauravk95** [google/filament#7308] opened 2023-10-27 15:15 UTC
**Describe the bug**
Black Screen in sample-hello-camera tested on Multiple device covering both Adreno and Mali GPU

**To Reproduce**
1. Build and run the Android Sample called  sample-hello-camera

**Expected behavior**
Camera preview is expected to be visible, but it remains black

**Screenshots**
N/A

**Logs**
Nothing suspicious found still adding logs here
```
2023-10-27 20:30:14.990  2414-2414  ziparchive              com....android.filament.hellocamera  W  Unable to open '/data/data/com.google.android.filament.hellocamera/code_cache/.overlay/base.apk/classes6.dm': No such file or directory
2023-10-27 20:30:14.991  2414-2414  ziparchive              com....android.filament.hellocamera  W  Unable to open '/data/app/~~KqumLR7LaW-cdd-fLYKl4g==/com.google.android.filament.hellocamera-xdNZMNdEgfNpDaIcVhnt7A==/base.dm': No such file or directory
2023-10-27 20:30:14.991  2414-2414  ziparchive              com....android.filament.hellocamera  W  Unable to open '/data/app/~~KqumLR7LaW-cdd-fLYKl4g==/com.google.android.filament.hellocamera-xdNZMNdEgfNpDaIcVhnt7A==/base.dm': No such file or directory
2023-10-27 20:30:15.019  2414-2414  nativeloader            com....android.filament.hellocamera  D  Configuring clns-4 for other apk /data/app/~~KqumLR7LaW-cdd-fLYKl4g==/com.google.android.filament.hellocamera-xdNZMNdEgfNpDaIcVhnt7A==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~KqumLR7LaW-cdd-fLYKl4g==/com.google.android.filament.hellocamera-xdNZMNdEgfNpDaIcVhnt7A==/lib/arm64:/data/app/~~KqumLR7LaW-cdd-fLYKl4g==/com.google.android.filament.hellocamera-xdNZMNdEgfNpDaIcVhnt7A==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.google.android.filament.hellocamera
2023-10-27 20:30:15.029  2414-2414  GraphicsEnvironment     com....android.filament.hellocamera  V  Currently set values for:
2023-10-27 20:30:15.029  2414-2414  GraphicsEnvironment     com....android.filament.hellocamera  V    angle_gl_driver_selection_pkgs=[]
2023-10-27 20:30:15.029  2414-2414  GraphicsEnvironment     com....android.filament.hellocamera  V    angle_gl_driver_selection_values=[]
2023-10-27 20:30:15.030  2414-2414  GraphicsEnvironment     com....android.filament.hellocamera  V  ANGLE GameManagerService for com.google.android.filament.hellocamera: false
2023-10-27 20:30:15.030  2414-2414  GraphicsEnvironment     com....android.filament.hellocamera  V  com.google.android.filament.hellocamera is not listed in per-application setting
2023-10-27 20:30:15.030  2414-2414  GraphicsEnvironment     com....android.filament.hellocamera  V  Neither updatable production driver nor prerelease driver is supported.
2023-10-27 20:30:15.038  2414-2478  vulkan                  com....android.filament.hellocamera  D  searching for layers in '/data/app/~~KqumLR7LaW-cdd-fLYKl4g==/com.google.android.filament.hellocamera-xdNZMNdEgfNpDaIcVhnt7A==/lib/arm64'
2023-10-27 20:30:15.038  2414-2478  vulkan                  com....android.filament.hellocamera  D  searching for layers in '/data/app/~~KqumLR7LaW-cdd-fLYKl4g==/com.google.android.filament.hellocamera-xdNZMNdEgfNpDaIcVhnt7A==/base.apk!/lib/arm64-v8a'
2023-10-27 20:30:15.039  2414-2478  DMABUFHEAPS             com....android.filament.hellocamera  I  Using DMA-BUF heap named: vframe-secure
2023-10-27 20:30:15.043  2414-2414  libEGL                  com....android.filament.hellocamera  D  loaded /vendor/lib64/egl/libGLES_mali.so
2023-10-27 20:30:15.093  2414-2414  Filament                com....android.filament.hellocamera  I  FEngine (64 bits) created at 0xb400007ae2f88dd0 (threading is enabled)
2023-10-27 20:30:15.094  2414-2512  Filament                com....android.filament.hellocamera  D  Using ASurfaceTexture
2023-10-27 20:30:15.094  2414-2512  Filament                com....android.filament.hellocamera  I  FEngine resolved backend: OpenGL
2023-10-27 20:30:15.100  2414-2512  Filament                com....android.filament.hellocamera  V  [ARM], [Mali-G78], [OpenGL ES 3.2 v1.r43p0-01eac0.5921042d0e5e9dcd76a86245576b4911], [OpenGL ES GLSL ES 3.20]
2023-10-27 20:30:15.100  2414-2512  Filament                com....android.filament.hellocamera  V  Feature level: 3
                                                                                                    Active workarounds: 
                                                                                                    vao_doesnt_store_element_array_buffer_binding
                                                                                                    dont_use_timer_query
                                                                                                    allow_read_only_ancillary_feedback_loop
2023-10-27 20:30:15.102  2414-2414  Filament                com....android.filament.hellocamera  I  Backend feature level: 3
2023-10-27 20:30:15.102  2414-2414  Filament                com....android.filament.hellocamera  I  FEngine feature level: 1
2023-10-27 20:30:15.113  2414-2414  Compatibil...geReporter com....android.filament.hellocamera  D  Compat change id reported: 236825255; UID 10710; state: DISABLED
2023-10-27 20:30:15.114  2414-2414  CameraManagerGlobal     com....android.filament.hellocamera  I  Connecting to camera service
2023-10-27 20:30:15.118  2414-2414  CameraHelper            com....android.filament.hellocamera  I  Selected camera 0.
2023-10-27 20:30:15.121  2414-2414  CameraHelper            com....android.filament.hellocamera  I  Highest resolution is 4032x3024.
2023-10-27 20:30:15.141  2414-2414  Compatibil...geReporter com....android.filament.hellocamera  D  Compat change id reported: 210923482; UID 10710; state: ENABLED
2023-10-27 20:30:15.146  2414-2414  Compatibil...geReporter com....android.filament.hellocamera  D  Compat change id reported: 237531167; UID 10710; state: DISABLED
2023-10-27 20:30:15.245  2414-2414  CameraHelper            com....android.filament.hellocamera  I  Created CaptureRequest.
2023-10-27 20:30:15.331  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27389): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:15.415  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27390): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:15.447  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27391): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:15.483  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27392): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:15.983  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27407): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:16.019  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27408): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:16.051  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27409): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:16.083  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27410): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:16.119  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27411): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:17.031  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27438): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:17.063  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27439): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:17.099  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27440): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:17.115  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27441): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:17.163  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27442): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:18.043  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27469): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:18.091  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27470): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:18.111  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27471): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:18.143  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27472): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:18.191  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27473): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:19.055  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27499): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:19.087  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27500): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:19.119  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27501): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera
2023-10-27 20:30:19.155  2414-2414  ent.hellocamera         com....android.filament.hellocamera  W  type=1400 audit(0.0:27502): avc:  denied  { getattr } for  name="/" dev="dmabuf" ino=1 scontext=u:r:untrusted_app_32:s0:c198,c258,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=filesystem permissive=0 app=com.google.android.filament.hellocamera

```

**Desktop (please complete the following information):**
 - OS: Mac OS 13.5.2
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: Pixel 6, Samsung A50, Realme GT Master
 - GPU: Mali-G78 MP20(Pixel 6), Mali-G72(Samsung A50), Adreno 642L(Realme GT master edition)
 - OS: Android 14, Android 13, Android 13
 - Backend: OpenGL ES

**Additional context**
I tried changing stream from using ImageReaders `it.hardwareBuffer` to Native stream and things seem to work then

```
        val surfaceTexture = SurfaceTexture(0)
        surfaceTexture.detachFromGLContext()
        this.surfaceTexture = surfaceTexture

        // Create the Android surface.
        this.surface = Surface(surfaceTexture)

        // Create the filament stream.
        filamentStream = Stream.Builder().stream(surfaceTexture).build(filamentEngine)

        // Create the Filament Texture object if we haven't done so already.
        if (filamentTexture == null) {
            filamentTexture = Texture.Builder()
                    .sampler(Texture.Sampler.SAMPLER_EXTERNAL)
                    .format(Texture.InternalFormat.RGB8)
                    .build(filamentEngine)
        }
```

**Comment by pixelflinger** [comment] 2024-01-26 19:52
duplicate of #6188

**Closed by pixelflinger** 2024-01-26 19:52 UTC
Labels: bug, duplicate, android
