### ISSUE TITLE
Metal errors during rendering

### ISSUE THREAD

**Issue by ast3rX** [google/filament#4097] opened 2021-06-07 17:57 UTC
**Describe the bug**
During rendering (camera interaction) Metal errors might appear in the log:

```
Execution of the command buffer was aborted due to an error during execution. Caused GPU Address Fault Error (IOAF code 11)
Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
```
The errors result in either corrupt frames / white frames or in the worst case a permanent hang.

After some investigation it is very likely that the bug was introduced in the following commit:
https://github.com/google/filament/commit/f0d99070e43d8bfc7dce6d77806e106458d9d26b

In previous versions rendering is stable. Would you mind double-checking the commit above if there is something wrong that can introduce address fault errors in Metal?

**Expected behavior**
No Metal errors and render artifacts.

**Desktop (please complete the following information):**
 - OS: iOS
 - Backend: Metal

**Comment by romainguy** [comment] 2021-06-07 18:31
Thanks, how do you repro this issue?

**Comment by ast3rX** [comment] 2021-06-09 19:31
I haven't seen this error in the filament example. I presume the sample scene is too simple to trigger this. I think it usually occured with lights and shadows, however turning off shadows, SSAO, and other post processing features didn't make the error disappear. I reverted the commit mentioned above and the issue seems to be gone.

**Comment by bejado** [comment] 2021-06-23 22:37
@ast3rX can you try turning on Xcode Shader Validation (Scheme -> Edit Scheme -> Diagnostics)?

**Comment by bejado** [comment] 2021-07-08 18:09
Closing, but feel free to reopen with more specific repro steps.

**Closed by bejado** 2021-07-08 18:09 UTC
Labels: bug, metal

**Comment by dandingol03** [comment] 2022-05-16 06:51
HI, @ast3rX . I reproduce some metal errors as below:

> 2022-05-16 14:30:31.335819+0800 DuTProduct3DSpaceModule[502:52463] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2022-05-16 14:28:42.008573+0800 DuTProduct3DSpaceModule[502:52073] Execution of the command buffer was aborted due to an error during execution. Caused GPU Address Fault Error (IOAF code 11)

**How to reproduce**
 I use `VertexBuffer` and `IndexBuffer` to draw two quad, and each quad is made up of six vertex. These two quad is rendered with some jpg texture, and i render an obj. However, these error would be dismissed if i add  `engine::flushAndWait` after i add each quad into the `scene`.

**Code about drawing a quad**


    const uint32_t w = filaView->getViewport().width;
    const uint32_t h = filaView->getViewport().height;
    const float aspectRatio = (float) w / h;
    int floatSize = 4;
    int vertexSize = 3 * floatSize + 2 * floatSize;

    int vertexCount = 4;
    float zOffset = 0.0f;
    
    float xScale = 0.957;
    //float xScale = 0.92f;
    float yScale = 0.957f / aspectRatio;


    const Vertex QUAD_VERTICES[4] = {
            {{1.0f * xScale * xScaleRatio, 1.0f * yScale * yScaleRatio, zOffset}, {1.0f, 1.0f}},
            {{ -1.0f *xScale * xScaleRatio, 1.0f * yScale * yScaleRatio, zOffset}, {0.0f, 1.0f}},
            {{-1.0f * xScale * xScaleRatio, -1.0f * yScale * yScaleRatio, zOffset}, {0.0f, 0.0f}},
            {{1.0f * xScale * xScaleRatio, -1.0f * yScale * yScaleRatio, zOffset}, {1.0f, 0.0f}}
    };

    VertexBuffer* vertexBuffer = VertexBuffer::Builder()
            .bufferCount(1)
            .vertexCount(vertexCount)
            .attribute(VertexAttribute:: POSITION, 0, VertexBuffer::AttributeType::FLOAT3, 0, vertexSize)
            .attribute(VertexAttribute::UV0, 0, VertexBuffer::AttributeType::FLOAT2, 3 * floatSize, vertexSize)
            .build(*engine);

    vertexBuffer->setBufferAt(*engine, 0, VertexBuffer::BufferDescriptor(QUAD_VERTICES, vertexSize * 4,
                                                                         nullptr));

    constexpr uint16_t QUAD_INDICES[6] = {
            (short) 0,
            (short) 1,
            (short) 3,
            (short )1,
            (short )2,
            (short )3,
            };

    IndexBuffer* indexBuffer = IndexBuffer::Builder()
            .indexCount(6)
            .bufferType(IndexBuffer::IndexType::USHORT)
            .build(*engine);
    indexBuffer->setBuffer(*engine,
                           IndexBuffer::BufferDescriptor(QUAD_INDICES, 12, nullptr));

    app.door = EntityManager::get().create();
    
    app.doorMat = params->setupFilamat(filamat_path);
    app.doorMaterialInstance = app.doorMat->createInstance();
    app.doorTexture = parseTexture("", TEXTURE_VIEWIMAGE);
    if (app.doorTexture != nullptr) {
        TextureSampler sampler;
        app.doorMaterialInstance->setParameter("baseColor", app.doorTexture, sampler);
    }

    RenderableManager::Builder(1)
    .boundingBox({{ 0.0f, 0.0f, 0.0f}, { 1.0f, 1.0f, 0.01f }})
    .geometry(0, RenderableManager::PrimitiveType::TRIANGLES, vertexBuffer, indexBuffer, 0, 6)
    .material(0, app.doorMaterialInstance)
    .build(*engine, app.door);

    
    if (scene != nullptr) {
        scene->addEntity(app.door);
        auto& tcm = engine->getTransformManager();
        auto ti = tcm.getInstance(app.door);
        mat4f transformMatrix =  mat4f{ mat3f(1.0f), float3(0.957f, 0.0f, 0.0f) } *
                math::mat4f();

        transformMatrix = mat4f::rotation(0.0 * math::d::DEG_TO_RAD,float3{ 0, 1, 0 }) * transformMatrix;
        
        transformMatrix = mat4f{ mat3f(1.0f), float3(-0.957f, 0.0f,  -1.0f) } * transformMatrix;
        tcm.setTransform(ti, transformMatrix);
        engine->flushAndWait();
    }
