### ISSUE TITLE
Normals are not smooth at triangle edges

### ISSUE THREAD

**Issue by elalish** [google/filament#1291] opened 2019-06-12 19:57 UTC
**Describe the bug**
The normals used for lighting calculations have discontinuities at the edges of triangles, making the mesh clearly visible in reflections. This is true both with and without a normal map for GLTF files. 

**To Reproduce**
1. Pull latest filament master and build.
2. run gltf_viewer Suzanne.glb or gltf_viewer SciFiHelmet.glb
Those files are Khronos test objects from here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0 and might require packaging (I used gltf-pipeline from node).

**Expected behavior**
Rendering with G1 continuity, rather than only G0, so that lighting is not discontinuous across triangle edges that have consistent material properties.

**Screenshots**
Suzanne, has no normal map:
![Screenshot from 2019-06-12 11-41-50](https://user-images.githubusercontent.com/1649964/59381795-2c609b80-8d11-11e9-8195-edcab628016d.png)
SciFiHelmet, including a normal map:
![Screenshot from 2019-06-12 11-44-58](https://user-images.githubusercontent.com/1649964/59381800-308cb900-8d11-11e9-8551-a2e0077ea06f.png)

**Desktop (please complete the following information):**
 - OS: gLinux
 - GPU: NVIDIA Quadro P1000
 - Backend: OpenGL

**Additional context**
This was originally noticed in the <model-viewer> fidelity comparisons to Filament, but has also been reproduced in SceneViewer. It does not appear to be a regression, as both current Filament and one pulled in February exhibit the same behavior.

**Comment by romainguy** [comment] 2019-06-12 20:06
I can repro the issue.

**Comment by romainguy** [comment] 2019-06-12 20:07
Philip, do these models come with normals or do we compute them ourselves?

**Comment by prideout** [comment] 2019-06-12 20:07
This model has pre-supplied tangents that look faceted even when rendering a simple visualization of `vertex_worldNormal`:

<img width="1362" alt="Screen Shot 2019-06-12 at 1 06 13 PM" src="https://user-images.githubusercontent.com/1288904/59382575-e0aef180-8d12-11e9-818d-9cc49a5633b8.png">

**Comment by prideout** [comment] 2019-06-12 21:05
Ah, the suzanne mesh has unwelded vertices because it has 11808 indices and 11808 vertices. The supplied normals in the model are smooth, but the supplied tangents are not.  See the following visualization of the tangent vectors.

![Screen Shot 2019-06-12 at 1 59 14 PM](https://user-images.githubusercontent.com/1288904/59386035-93368280-8d1a-11e9-8218-8791cb10000f.png)

This explains why it looks faceted in Filament, but I'm not sure yet why the mesh looks smooth in ThreeJS and BabylonJS.  Let's figure that out before closing this and opening a follow-up bug against the glTF conformance suite.

(@donmccurdy this is an interesting one!)

**Comment by prideout** [comment] 2019-06-12 22:27
ThreeJS ignores the model's tangents unless normal mapping is enabled, so the faceted tangents in the model do not matter.

Filament packs the provided tangents and normals into a basis quaternion on the CPU, then unpacks them on the GPU.  Since the model is providing a non-orthonormal basis, Filament unpacks bad normals from the quats.

**Comment by romainguy** [comment] 2019-06-12 22:53
Note that the issue is in our gltf loader that SceneViewer does *not* use. They may have a bug on their side too. Rendering is not the problem here.

**Comment by elalish** [comment] 2019-06-12 23:06
Also, if ThreeJS does use the tangents when normal mapping is enabled, why do they properly render SciFiHelmet (which has a normal map)? Is it just that they don't turn them into a quaternion?

**Comment by elalish** [comment] 2019-06-12 23:12
What are the tangents in GLTF intended to specify?

**Comment by prideout** [comment] 2019-06-12 23:14
The "fix" is not in the glTF loader, it's in the tangents utility, which
SceneViewer might be using.

**Comment by romainguy** [comment] 2019-06-12 23:21
Ah you're right, my bad they might be using this utility.

**Comment by prideout** [comment] 2019-06-12 23:40
@elalish: ThreeJS preserves normals so if there are bad tangents in other models like SciFiHelmet, then the issue would manifest only as a subtle effect on the normal map, it would not affect lighting as it does in Filament.

**Closed** 2019-06-12 23:44 UTC
Labels: gltfio

**Comment by prideout** [comment] 2019-06-12 23:50
@McNopper we noticed that VKTS-exported models have faceted tangent vectors, and are unwelded.  Not sure if VKTS is still extant but thought you should know.

**Comment by McNopper** [comment] 2019-06-13 16:34
I am suprised, that some folks still are using VKTS :-)
Thanks a lot for the info, but we 100% focus on glTF and dropped our proprietary format VKTS.
So, the VKTS exporter - if it is still somewhere out there - is not supported anymore.

**Comment by cdata** [comment] 2019-06-13 16:46
The described artifact occurs in some of the canonical glTF sample models. It sounds like perhaps the related glTF sample models could stand to be cleaned up a bit?

**Comment by prideout** [comment] 2019-06-13 17:00
@cdata I filed [issue 226](https://github.com/KhronosGroup/glTF-Sample-Models/issues/226) against the Khronos repo, feel free to add to its comments.
