### ISSUE TITLE
skybox is different performance in debug and release environments.

### ISSUE THREAD

**Issue by Daisiyou** [google/filament#7151] opened 2023-09-08 08:50 UTC
**Describe the bug**
in demo gltf-viewer(filament 1.41.0)

choose: Metal Debug:
![IMG_0466](https://github.com/google/filament/assets/14085395/e61a9022-7e07-433e-bd05-e69cd6e842dd)

choose: Metal Release:
![IMG_0467](https://github.com/google/filament/assets/14085395/01a896e7-aefc-4d3d-af7f-c1001aa0461b)

How can I get the same result？

**Comment by suzp1984** [comment] 2023-09-08 14:03
It is the ios sample located at `ios/samples/gltf-viewer`, you'd better describe the issue clearly.

**Comment by Daisiyou** [comment] 2023-09-09 03:53
> It is the ios sample located at `ios/samples/gltf-viewer`, you'd better describe the issue clearly.

yes, it is located at `ios/samples/gltf-viewer`.

**Comment by suzp1984** [comment] 2023-09-09 10:21
I reproduced this bug on the latest `main` branch build. (iphone 11, ios 16.6.1). 
One thing I can make sure is that the bug is in one of the static libraries located at `out/ios-release/filament/lib/arm64`.
<img width="888" alt="Screenshot 2023-09-09 at 6 04 43 PM" src="https://github.com/google/filament/assets/2757043/85c82f71-c0fd-431b-940b-64e642a44971">

If I replace the `Metal Debug`'s `Libaray Search Path` to `out/ios-release/filament/lib/arm64`, then the `Metal debug` build will has same issue. 
And If I replace the `Metal Release`'s `Library Search Path` to `out/ios-debug/filament/lib/arm64`, then the `Metal release` build will be good without this issue.

So which static library is the cause? It's not easy to replace them one by one, will met some `assert` error at runtime. I only confirmed the `libktxreader.a` & `libibl.a` is ok.

Because I don't understand the `filament` well now, that's what I can do now. But I can still guess the problem is the `skybox & IBL`, the `skybox` & `IBL` resource is fine, above `libktxreader.a` & `libibl.a` do the related job. Maybe it is the the transform matrix problem or the metal shaders that do the skybox rendering problem, I don't know.

<img width="860" alt="Screenshot 2023-09-09 at 6 09 56 PM" src="https://github.com/google/filament/assets/2757043/49a98998-9857-42df-82eb-9ff5ce36bfe3">

Check the linker libraries in xcode, `-lktxreader` linked twice, that's a duplicated mistake. At least I found something, ah.

**Comment by suzp1984** [comment] 2023-09-11 06:54
I can debug the metal rendering in xcode, what I found the skybox metal shaders are so different between debug & release build. 

So, I suspect it's the release build's skybox vert/frag shaders problem.

**Comment by romainguy** [comment] 2023-09-11 16:56
Release build shaders are optimized via spirv-opt, so the shaders are expected to be different.

**Comment by Daisiyou** [comment] 2023-09-15 05:16
Is there any way to get the same result？

**Comment by suzp1984** [comment] 2023-11-12 09:45
I compared the fragment shaders of skybox render pipeline for the debug and release.

<img width="836" alt="Screenshot 2023-11-12 at 5 23 44 PM" src="https://github.com/google/filament/assets/2757043/dbda481b-5351-4c62-975b-894c85979270">

Above code is the debug version do the skybox texture sample.

Below code is the release version do the skybox texture sample. Check the release version's optimizations: convert `float4` ->  `half4` -> `float4`.
 
![Screenshot 2023-11-12 at 5 24 29 PM](https://github.com/google/filament/assets/2757043/9797de84-5eee-4607-b4de-387e9a6453fc)


The value of `variable_eyeDirection` is a so huge one. `in.variable_eyeDirection = [838264916237353000.0, 3227688676225974300.0, ...]`.

I guess `838264916237353000.0` must be out of the range of `half`.

so `float3(half4(in.variable_eyeDirection).xyz` may be the root cause of this bug.

If it's the root cause, I guess there are two solutions.
1. `in.variable_eyeDirection`: normalize its value in range of `half` or maybe `[-1, 1]`;
2. don't do optimization of `float` -> `half` for the metal shader;

**Comment by bejado** [comment] 2023-12-28 19:19
After some investigation, I believe this is a bug in our material pipeline—most likely with Khronos's spirv-opt or spirv-cross. Even though we tag the `eyeDirection` variable as `highp`, it gets demoted to a `half4` in the fragment shader for reasons I don't understand. That being said, we should be able to reduce the magnitude of the `eyeDirection` vector in the vertex shader to help precision.

Those huge numbers are the result of [this code](https://github.com/google/filament/blob/e2da13f81734ccd6d6f9935061b771801682619e/shaders/src/getters.vs#L257-L264). The Skybox vertices are defined in clip space on the [far
plane (z = 1)](https://github.com/google/filament/blob/e2da13f81734ccd6d6f9935061b771801682619e/filament/src/details/Engine.cpp#L178-L182). The way the math works out requires us to divide by a very small number to avoid dividing by zero.

One solution is to simply not divide by w, which is allowed because we're only using the xyz coordinates as a direction in the fragment shader. This code works for me and fixes the precision issue:

```
void materialVertex(inout MaterialVertexInputs material) {
    mat4 transform = getWorldFromClipMatrix();
    vec4 p = getPosition();
    // GL convention to inverted DX convention
    p.z = p.z * -0.5 + 0.5;
    vec4 position = transform * p;
    material.eyeDirection.xyz = position.xyz;
}
```

I'll look into getting this merged into Filament.

**Comment by oleg-komaristov-mobiline** [comment] 2023-12-28 19:40
Any news regarding this issue?
I found an issue that can have the same source:

The skybox created from the [backyard-garden](https://hdri-haven.com/hdri/backyard-garden) HDR file works well when the Filament is built in debug mode and doesn't work in the release build.
You can quickly reproduce the issue by replacing the skybox in the 'gltf-viewer' example.
The current release (1.49) affected.

**Closed** 2024-03-22 19:03 UTC
Labels: ios, metal
